### ISSUE TITLE
Puerto por defecto Mediaserver

### ISSUE THREAD

**Issue by mafede** [alfa-addon/addon#104]
Me he aficionado a alfa por MEDIASERVER, y casi que me gusta más que como plugin de Kodi. 

Se puede cambiar el puerto por defecto que utiliza el mediacenter (el 8080). Me han cambiado el router por un livebox de Jazztel, y ese puerto es exclusivo para gestión del router, y no se como cambiarlo desde el router, y por eso he pensado en cambiar el mediacenter si fuera más fácil.

Gracias

**Comment by mafede** [comment]
Me contesto yo mismo

Como desde dentro de mi red, si es accesible el 8080, he decidido crear un puerto externo inventado que se redirigan de forma interna al 8080.

Así que este punto ha quedado solucionado.

**Comment by alfa-addon** [comment]
El puerto se puede configurar desde el propio addon en la configuración o editando manualmente el fichero settings.
Cerramos la issue.

**Comment by mafede** [comment]
Gracias
