### ISSUE TITLE
TValacarta y Alfa para Plex

### ISSUE THREAD

**Issue by mafede** [alfa-addon/addon#105]
La evolución de pelisalacarta como alfa me parece genial, y gracias a este cambio he descubierto la configuración por mediaserver que no había utilizado anteriormente.

¿Está prevista la creación de Alfa para Plex?

¿esta prevista crear una versión mediaserver del plugin de tvalacarta?

Gracias

**Comment by alfa-addon** [comment]
Hola, sobre sus dudas:

No habrá versión de Plex si no se incorpora alguien que lo desarrolle.

Sobre versión mediaserver de tvalacarta, el equipo de alfa no tiene intención de hacer un fork de tvalacarta ya que el plugin no ha sido abandonado como pasó con el de pelis.
Estudiaremos la opción de añadir canales "en vivo" a Alfa.

Saludos.

**Comment by mafede** [comment]
Gracias, por la contestación.

**Comment by alfa-addon** [comment]
De nada!

Saludos
