### ISSUE TITLE
plz playhydrax add ?

### ISSUE THREAD

**Issue by lavara123** [alfa-addon/addon#1067]
id: e.i,
useP2P: n.use_p2p,
sources: n.sources,
source_breaks: n.source_breaks,
domain: n.domain,
 md5_id: n.md5_id,
user_id: n.user_id,
preview: n.preview,
 tracks: e.h.tracks || [],
configJwp: e.h || {}

**Comment by SistemaRayoXP** [comment]
Could you please explain yourself? Your comment isn't very understandable 😵

**Comment by lavara123** [comment]
> Could you please explain yourself? Your comment isn't very understandable 😵

playhydrax not working

https://github.com/alfa-addon/addon/blob/5f9fd03974104cfb552ffb14cbe281e7bb694556/plugin.video.alfa/channels/animeflv_ru.py#L335

@alfa-addon

**Comment by SistemaRayoXP** [comment]
At the moment, that module isn't being maintained, sorry about that
