### ISSUE TITLE
Alfa Addon no funciona a través de interface web para control remoto de Kodi (Chorus)

### ISSUE THREAD

**Issue by PachisPachis** [alfa-addon/addon#1152]
Buenas 

Utilizo el addon en parte como gestor de descargas, pienso que sería bueno poderlo controlar mediante la interface web de Kodi, de hecho lo he intentado y aunque arranca, no termina de funcionar.

Por ejemplo si le doy a buscar una peli, tras confirmar cuál es, se supone que tendría que hacer las búsquedas en los canales configurados pero se queda esperando indefinidamente en Loading Folder:

![image](https://user-images.githubusercontent.com/13168161/166222339-22b8b17c-dcf4-4f76-a95d-e344cd2ddefe.png)

He revisado el log de Kodi y esto es lo que me encuentro:

`2022-05-02 12:43:46.602 T:19304   DEBUG <CWebserver[8080]>: request received for /jsonrpc?FileCollection
2022-05-02 12:43:46.602 T:19304   DEBUG <general>: CUtil::GetMatchingSource: no matching source found for [/osYbtvqjMUhEXgkuFJOsRYVpq6N.jpg]`

¿Hay algo que se pueda hacer para que funcione vía web?.

Un saludo.

**Comment by lopezvg** [comment]
Nunca ha sido la intención que Alfa funcionara desde el interfaz web de Kodi
