### ISSUE TITLE
hdfull

### ISSUE THREAD

**Issue by advidsec** [alfa-addon/addon#1193]
Es imposible loguearse con el plugin de hdfull, segun el log da fallo en el login habiendo probado con varios dominios que funcionan, ni idea si han cambiado la forma de loguearse o es la proteccion de cloudfare (probe a cambiarlo de 3 a 10 intentos y ni asi).
Segun comentan en hdfull en twitter el plugin de alfa no les gusta nada porque segun ellos hace ddos, ni idea si han bloqueado o algo.

**Comment by lopezvg** [comment]
https://alfa-addon.com/threads/hdfull-modifico-el-loggin-de-nuevo.4945/post-16380
