### ISSUE TITLE
Premiumize support

### ISSUE THREAD

**Issue by reddit-reaper** [alfa-addon/addon#1200]
Por favor puedes agregar Premiumize debrid en el addon? es como real-debrid. si necesitas cuenta dejame saber

**Comment by alfa-addon** [comment]
No agregamos servidores de pago

**Comment by aranapatona** [comment]
"No agregamos servidores de pago"
pero tienen soporte para alldebrid y real debrid, es lo mismo.

**Comment by reddit-reaper** [comment]
> "No agregamos servidores de pago" pero tienen soporte para alldebrid y real debrid, es lo mismo.

exactamente
