### ISSUE TITLE
side menu

### ISSUE THREAD

**Issue by numbernumero** [alfa-addon/addon#1243]
Hi the "SIDE MENU"  does not work perfectly. If I click on "Menú Clasico" nothing happens but only the reload of the same page. "Donde Buscar" doesn't work either.
Thank you for your hard work

**Comment by alfa-addon** [comment]
Fixed.  Thanks for reporting

**Comment by numbernumero** [comment]
Hi, I don't know if there was an error in the last update but the problems in the side menu remained the same
