### ISSUE TITLE
Hi, I don't know if there was an error in the last update but the problems in the side menu remained the same

### ISSUE THREAD

**Issue by numbernumero** [alfa-addon/addon#1245]
Hi, I don't know if there was an error in the last update but the problems in the "SIDE MENU" remained the same. 
"Menú Clasico"  and "Donde Buscar" seem to be not working
_Originally posted by @numbernumero in https://github.com/alfa-addon/addon/issues/1243#issuecomment-1616086684_

**Comment by alfa-addon** [comment]
The error I found based on your report has been fixed.  However, if you still have problems, please report them appropriately following this rules: https://alfa-addon.com/link-forums/pasos-para-un-correcto-reporte-de-error.24/
