### ISSUE TITLE
Serieslan no se muestra

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#1248]
Al tratar de elegir desde [Series] a SeriesLan, muestra un mensaje de "Puede deberse a un error de conexion, cambio de estructura en la web ..."

Tiene tiempo este error (meses), pero sigue presentando en Libreleec Leia 18.9 en plataforma Raspberry Pi 3

**Comment by alfa-addon** [comment]
El canal SeriesLan ha sido reparado y remasterizado,  Reinicia Kodi y prueba de nuevo.  Gracias por reportarlo.

**Comment by askotx** [comment]
Cierto, gracias!
