### ISSUE TITLE
remove favourites 

### ISSUE THREAD

**Issue by numbernumero** [alfa-addon/addon#1270]
Hi, in Android (firestick) you cannot remove favorites via context menu. The only way is eliminate them from Kodi favorites

**Comment by DieFeM** [comment]
He hecho una prueba, y si que se borra, pero no se refleja en los favoritos de Kodi hasta que reinicias el programa. Sin embargo, si lo haces desde los favoritos de Kodi, Alfa lo refleja correctamente.
Lo que hace Alfa es editar favourites.xml, por lo que deduzco que Kodi usa algún tipo de caché que habría que encontrar la manera de refrescar tras editar el xml.

**Comment by DieFeM** [comment]
Buscando por internet he dado con varios foros en los que buscan solución, y parece ser que no lo mas parecido es basicamente recargar el perfil, que es casi como reiniciar kodi.
[](https://forum.kodi.tv/showthread.php?tid=338465)

**Comment by SistemaRayoXP** [comment]
Gracias por aclarar la causa del problema, me ha ayudado a dar con una posible solución.

Dado que es una peculiaridad muy molesta, me puse a revisar superficialmente cómo funciona el código de los favoritos de Kodi internamente, partiendo de la API JSON-RPC que podemos usar desde dentro del add-on.

<details>
<summary>Aquí viene la explicación larga de cómo llegué a la siguiente conclusión:</summary>

> Comenzamos aquí, donde hay este método que añade un favorito, por ende, modifica el archivo, pero también actualiza Kodi:
> https://github.com/xbmc/xbmc/blob/7cc345d620d3efd6d869bc5d7e8dc2c1d69c4312/xbmc/interfaces/json-rpc/schema/methods.json#L6627
> 
> Dicho archivo enlaza con la siguiente función de C++ (`CFavouritesOperations::AddFavourite`):
> https://github.com/xbmc/xbmc/blob/7cc345d620d3efd6d869bc5d7e8dc2c1d69c4312/xbmc/interfaces/json-rpc/JSONServiceDescription.cpp#L238
> 
> Esa función está descrita en el siguiente archivo, lo interesante de dicha función es la línea 157, que llama a un método con un nombre interesante (`CServiceBroker::GetFavouritesService().AddOrRemove`):
> https://github.com/xbmc/xbmc/blob/7cc345d620d3efd6d869bc5d7e8dc2c1d69c4312/xbmc/interfaces/json-rpc/FavouritesOperations.cpp#L157
> 
> Y esa función, sin mucho rodeo (que básicamente llama al servicio de caché que llama a los favoritos y actualiza la caché) se define aquí:
> https://github.com/xbmc/xbmc/blob/7cc345d620d3efd6d869bc5d7e8dc2c1d69c4312/xbmc/favourites/FavouritesService.cpp#L222
> Lo interesante es precisamente la línea 222, que indica que, si el favorito que se pase ya existe, se elimina. Por ende, si llamamos a la API JSON-RPC en su función `Favourites.AddFavourite` con los parámetros de un favorito existente, se detectará como ya existente y se entenderá que se desea eliminar. Nos devolverá OK, como si lo hubiese añadido, pero en realidad lo habrá eliminado.

</details>

En resumen, @DieFeM, prueba con la API JSON-RPC mediante el método `Favourites.AddFavourite`, pasando los parámetros de un favorito existente. En teoría, debería de eliminarlo. El código más o menos se vería así:
```
import json
import xbmc
from platformcode import logger

request = {
  "jsonrpc": "2.0",
  "method": "Favourites.AddFavourite",
  "params": {
    "title": "Canales",
    "type": "folder",
    "path": "plugin://plugin.video.alfa/?abc1234567890def",
    "thumbnail": "/path/to/thumbnail.jpg"
  },
  "id": 1
}

response = json.loads(xbmc.executeJSONRPC(json.dumps(request)))
logger.info(response)
```

Puedes jugar con la API para, por ejemplo, recuperar los favoritos, y así obtener la versión más reciente que tenga Kodi (que puede no ser la del archivo). Cambiarías el diccionario a lo siguiente, pero lo demás es lo mismo:
```
request = {
  "jsonrpc": "2.0",
  "method": "Favourites.GetFavourites",
  "id": 1
}
```

**Comment by SistemaRayoXP** [comment]
Mayormente ya quedó solucionado, aunque queda pendiente lo de renombrar favoritos. Lo cierro como completado.
