### ISSUE TITLE
Problema en Linux con Cryptodome desde la 3.9.12 [Arreglado]

### ISSUE THREAD

**Issue by tonikelope** [alfa-addon/addon#1285]
Parece que el módulo Cryptodome no se encuentra.

`from Cryptodome.Cipher import AES`

Ha empezado a pasar justo ahora que acabo de actualizar de la 3.9.11 a la 3.9.12

Estoy en ArchLinux pero me pasa también en CoreElec (bajando a la 3.9.11 funciona OK)

**Comment by SistemaRayoXP** [comment]
Bueno, pues te cuento que el dev que leía mentes se fue con los aliens. ¿Y el log?

**Comment by tonikelope** [comment]
[kodi-F7P2B0U1YT.log](https://github.com/alfa-addon/addon/files/13232507/kodi-F7P2B0U1YT.log)

**Comment by SistemaRayoXP** [comment]
Mi error. Deja te explico. Es necesario que envíes el crashlog, o al menos el último log donde Kodi se cerró.

Este usualmente se guarda en tu carpeta de usuario tipo /home/<tu_nombre_de_usuario>/kodi_crashlog-YYYYMMDD_HHMMSS.log

El último log de Kodi se suele guardar en .kodi/temp/kodi.old.log

Cualquiera de esos podría dar pistas de lo que te va mal, pero es necesario que sea un log donde Kodi se te haya cerrado, para saber exactamente qué estabas haciendo cuando falló

**Comment by SistemaRayoXP** [comment]
Perdona el anterior mensaje, no he leído bien tu mensaje inicial

**Comment by tonikelope** [comment]
KODI no se cierra. Sale el mensaje de ALFA de que se ha producido un error.

Tengo un canal de un foro con enlaces de MEGA que usa AES. Como decía, hasta la 3.9.11 (incluida) sin problema. De hecho acabo de bajar a la 3.9.11 y no da el error, todo funciona OK. 

Salu2 ;)

**Comment by SistemaRayoXP** [comment]
Ok, el problema es simple. Actualmente los módulos de Python en Linux están expuestos a Kodi debido a que se integran a la variable sys.path. Sin embargo, Kodi viene con sus propias versiones de los módulos.

Debido a que los módulos del sistema se exponían a Kodi, el intérprete de Python de Kodi los tomaba antes que sus propios módulos, incluso cuando los módulos no están instalados en Kodi. Esto generaba crasheos aleatorios en Alfa, por lo que en la 3.9.12+ decidimos parchar este "bug" eliminando las rutas a los paquetes del sistema de sys.path. Alfa no utiliza el módulo pycryptodome, por lo que no está disponible en las rutas por defecto de Kodi.

La alternativa es que añadas pycryptodome a tu carpeta lib

**Comment by tonikelope** [comment]
Hola. Sí, claro, es lógico. Además ley el mensaje del foro sobre este tema.
Lo que no estoy seguro es cómo funciona entonces el conector de MEGA bajo
Linux y Android si no está Cryptodome.

Para Windows importa el _AES.pyd ¿pero en Linux?

Gracias por el trabajo.

Un saludo.

**Comment by SistemaRayoXP** [comment]
Malas prácticas debido a la cantidad de manos que han trabajado en el add-on. Efectivamente, rompió Mega. Lo más seguro es que solo se necesite meter el módulo a lib. Está pendiente de revisarse por parte del equipo.

Te informaremos los avances al respecto

**Comment by tonikelope** [comment]
Ya imagino. Encantado de poder ayudar.

Un saludo.

**Comment by SistemaRayoXP** [comment]
Hola. Prueba con la 3.9.13.fix6. Hicimos un arreglo algo sucio pero funcional. Las bibliotecas Cryptodome y PIL deberían estar disponibles en el lib de Alfa como enlaces simbólicos, que es preferible a tener las rutas *-packages

**Comment by tonikelope** [comment]
Instalado el fix y probado.

ArchLinux: OK

**CoreElec: ERROR** (dejo log)

[kodi.log](https://github.com/alfa-addon/addon/files/13296196/kodi.log)

Parece según el log que falla al hacer el import pero si se hace el import desde el intérprete de CoreElec no hay error.

```
Python 3.11.2 (main, Jun 30 2023, 08:55:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome.Cipher import AES
>>> 
```

En ambos casos he comprobado que se crean los enlaces simbólicos correctamente dentro de lib apuntando a los directorios del sistema que también he comprobado que existen tanto en ArchLinux como en CoreElec. Además, como digo en la 3.9.11 no se da este error en Arch ni en CoreElec. 

CoreELEC:~/.kodi/addons/plugin.video.alfa/lib # ls -alh
total 3M     
drwxr-xr-x   29 root     root        4.0K Nov  8 12:16 .
drwxr-xr-x   11 root     root        4.0K Nov  8 11:51 ..
-rw-r--r--    1 root     root      278.3K Nov  8 11:51 AlfaChannelHelper.py
drwxr-xr-x    5 root     root        4.0K Nov  8 11:51 Crypto
lrwxrwxrwx    1 root     root          44 Nov  8 11:51 Cryptodome -> /usr/lib/python3.11/site-packages/Cryptodome
-rw-r--r--    1 root     root        4.9K Nov  8 11:51 MultipartPostHandler.py
lrwxrwxrwx    1 root     root          37 Nov  8 11:51 PIL -> /usr/lib/python3.11/site-packages/PIL
-rw-r--r--    1 root     root           0 Nov  8 11:51 __init__.py
drwxr-xr-x    2 root     root        4.0K Nov  8 12:16 __pycache__
-rw-r--r--    1 root     root        2.2K Nov  8 11:51 aadecode.py
-rw-r--r--    1 root     root       95.2K Nov  8 11:51 alfa_assistant.py
-rw-r--r--    1 root     root      191.9K Nov  8 11:51 alfaresolver.py
-rw-r--r--    1 root     root      290.1K Nov  8 12:16 alfaresolver_py3.py
-rw-r--r--    1 root     root      198.3K Nov  8 11:51 alfaresolver_py3_3_06.py
-rw-r--r--    1 root     root      176.6K Nov  8 11:51 alfaresolver_py3_3_07.py
-rw-r--r--    1 root     root      177.1K Nov  8 11:51 alfaresolver_py3_3_08.py
-rw-r--r--    1 root     root      176.8K Nov  8 11:51 alfaresolver_py3_3_09.py
-rw-r--r--    1 root     root      176.6K Nov  8 11:51 alfaresolver_py3_3_10.py
-rw-r--r--    1 root     root      290.1K Nov  8 11:51 alfaresolver_py3_3_11.py
drwxr-xr-x    4 root     root        4.0K Nov  8 11:51 assistant
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 bencode
-rw-r--r--    1 root     root      148.5K Nov  8 11:51 bottle.py
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 brotlipython
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 btserver
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 builtins
drwxr-xr-x    6 root     root        4.0K Nov  8 11:51 cloudscraper
-rw-r--r--    1 root     root       15.8K Nov  8 11:51 dumprar.py
drwxr-xr-x   10 root     root        4.0K Nov  8 11:51 future
-rw-r--r--    1 root     root      197.0K Nov  8 11:51 generictools.py
-rw-r--r--    1 root     root       11.9K Nov  8 11:51 gktools.py
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 html
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 http
-rw-r--r--    1 root     root        8.3K Nov  8 11:51 jjdecode.py
drwxr-xr-x   11 root     root        4.0K Nov  8 11:51 js2py
-rw-r--r--    1 root     root        3.0K Nov  8 11:51 jsc.py
-rw-r--r--    1 root     root       19.4K Nov  8 11:51 jscrypto.py
-rw-r--r--    1 root     root        8.4K Nov  8 11:51 jsinterpreter.py
-rw-r--r--    1 root     root        6.4K Nov  8 11:51 jsunpack.py
-rw-r--r--    1 root     root        1.8K Nov  8 11:51 kt_player.py
drwxr-xr-x    3 root     root        4.0K Nov  8 11:51 megaserver
drwxr-xr-x    7 root     root        4.0K Nov  8 11:51 past
-rw-r--r--    1 root     root        2.7K Nov  8 11:51 players_parse.py
-rw-r--r--    1 root     root        9.8K Nov  8 11:51 polling2.py
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 pyaes
-rw-r--r--    1 root     root       11.2K Nov  8 11:51 pyberishaes.py
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 pyjsparser
drwxr-xr-x    4 root     root        4.0K Nov  8 11:51 pym
-rw-r--r--    1 root     root      267.0K Nov  8 11:51 pyparsing.py
drwxr-xr-x   19 root     root        4.0K Nov  8 11:51 python_libtorrent
drwxr-xr-x    4 root     root        4.0K Nov  8 11:51 quasar
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 queue
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 rJs
-rw-r--r--    1 root     root      101.8K Nov  8 11:51 rarfile.py
-rw-r--r--    1 root     root       89.5K Nov  8 11:51 rarfile_py2.py
drwxr-xr-x   18 root     root        4.0K Nov  8 11:51 rarfiles
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 reprlib
drwxr-xr-x   10 root     root        4.0K Nov  8 11:51 requests_toolbelt
drwxr-xr-x    2 root     root        4.0K Nov  8 11:51 rijndael
drwxr-xr-x    5 root     root        4.0K Nov  8 11:51 sambatools_py2
drwxr-xr-x    5 root     root        4.0K Nov  8 11:51 sambatools_py3
-rw-r--r--    1 root     root        1.3K Nov  8 11:51 servop.py
-rw-r--r--    1 root     root       34.0K Nov  8 11:51 six.py
-rw-r--r--    1 root     root         525 Nov  8 11:51 strptime_fix.py
-rw-r--r--    1 root     root       17.9K Nov  8 11:51 unshortenit.py
-rw-r--r--    1 root     root       18.6K Nov  8 11:51 xmltodict.py

Como detalle, en CoreElec el directorio /usr/lib/python3.11/site-packages/Cryptodome es un enlace simbólico a /usr/lib/python3.11/site-packages/Crypto (En ArchLinux no, Cryptodome es un directorio normal).

CoreELEC:/usr/lib/python3.11/site-packages # ls -alh
total 145K   
drwxrwxr-x   12 root     root         395 Jun 30 09:15 .
drwxrwxr-x   33 root     root        3.7K Jun 30 09:15 ..
drwxrwxr-x   11 root     root         207 Jun 30 08:56 Crypto
lrwxrwxrwx    1 root     root          40 Jun 30 08:56 Cryptodome -> /usr/lib/python3.11/site-packages/Crypto
drwxrwxr-x    2 root     root        2.3K Jun 30 08:57 PIL
drwxrwxr-x    2 root     root         135 Jun 30 08:57 Pillow-9.3.0-py3.11.egg-info
-rw-r--r--    1 root     root         837 Jun 30 08:57 PyGObject-3.42.2.egg-info
-rw-r--r--    1 root     root         119 Jun 30 08:55 README.txt
-rwxr-xr-x    1 root     root      127.6K Jun 30 08:57 _dbus_bindings.so
-rwxr-xr-x    1 root     root       13.9K Jun 30 08:57 _dbus_glib_bindings.so
drwxrwxr-x    3 root     root         335 Jun 30 08:57 dbus
drwxr-xr-x    2 root     root          29 Jun 30 08:57 gi
drwxrwxr-x    4 root     root         136 Jun 30 09:15 kodi
drwxrwxr-x    8 root     root         540 Jun 30 08:56 pgi
-rw-rw-r--    1 root     root         742 Jun 30 08:56 pgi-0.0.11.2-py3.11.egg-info
drwxrwxr-x    2 root     root         119 Jun 30 08:56 pycryptodome-3.16.0-py3.11.egg-info
drwxrwxr-x    2 root     root         188 Jun 30 08:56 simplejson
drwxrwxr-x    2 root     root          99 Jun 30 08:56 simplejson-3.18.1-py3.11.egg-info

Cualquier otra información que necesites dime. 

Gracias.

Salu2 ;)

**Comment by tonikelope** [comment]
Hola. ¿Hay algún avance en esto? En la 3.9.15 sigue dando el mismo error en CoreElec.

**Comment by SistemaRayoXP** [comment]
Ayer haciendo unas pruebas con otros módulos encontré una potencial solución. No es tan "invisible" como la solución previa, pero debería ser más efectiva.

Descomprime lo de aquí [patch.zip](https://github.com/alfa-addon/addon/files/13641195/patch.zip) en tu instalación de Alfa.

En donde utilices cualquier librería de crypto, escribe:
```
import patch

patch.unfix_path()
import Cryptodome
patch.fix_path()
```

**Comment by SistemaRayoXP** [comment]
Hola. ¿Algún avance?

**Comment by tonikelope** [comment]
Hola. Probado el último parche y confirmo que FUNCIONA tanto en ArchLinux como en CoreElec 

Muchas gracias por la ayuda.

Salu2 ;)
