### ISSUE TITLE
Allcalidad no funciona

### ISSUE THREAD

**Issue by italfire** [alfa-addon/addon#1292]
### ¿Verificaste que el error es de Alfa?

- [x] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://paste.kodi.tv/azelahukev.kodi

### Sistema operativo

Windows 10

### Versión de Alfa

3.9.14

### Versión de Kodi

Kodi 20

### Descripción del problema

El canal "Allcalidad" no funciona.  Aparece un mensaje  "The server on wich is hosted is not yet supported by Alfa"

**Comment by italfire** [comment]
If it helps, I've edited the findvideos locally and it seems to work fine.

def findvideos(item):
    logger.info()
    
    itemlist = []
    encontrado = []
    
    data = httptools.downloadpage(item.url, encoding=encoding, forced_proxy_opt=forced_proxy_opt, canonical=canonical).data
    patron  = 'data-target="[^"]+" data-url="([^"]+)">\s*([^<]+)'

    matches = scrapertools.find_multiple_matches(data, patron)
    
    for url, title in matches:
        #data = httptools.downloadpage(url, canonical=canonical).data
        #patron = "var url = '([^']+)'"
        #url = scrapertools.find_single_match(data, patron)
        if "Vip" in title:
            continue
        
        itemlist.append(Item(
                        channel=item.channel,
                        contentTitle=item.contentTitle,
                        contentThumbnail=item.thumbnail,
                        infoLabels=item.infoLabels,
                        language="Latino",
                        title='%s', action="play",
                        url=url
                       ))

    itemlist = servertools.get_servers_itemlist(itemlist, lambda i: i.title % i.server.capitalize())

    tmdb.set_infoLabels_itemlist(itemlist, __modo_grafico__)

    # Requerido para FilterTools
    itemlist = filtertools.get_links(itemlist, item, list_language)

    # Requerido para AutoPlay

    autoplay.start(itemlist, item)

    if itemlist and item.contentChannel != "videolibrary":
        itemlist.append(Item(channel=item.channel))
        itemlist.append(item.clone(channel="trailertools", title="Buscar Tráiler", action="buscartrailer", context="",
                                   text_color="magenta"))

        # Opción "Añadir esta película a la videoteca de KODI"
        if config.get_videolibrary_support():
            itemlist.append(Item(channel=item.channel, title="Añadir a la videoteca", text_color="green",
                                 action="add_pelicula_to_library", url=item.url, thumbnail = item.thumbnail,
                                 contentTitle = item.contentTitle
                                 ))
    return itemlist

**Comment by SistemaRayoXP** [comment]
Thanks for the report. It should be working with the last fix (3.9.14.fix6)
