### ISSUE TITLE
Sección Canales Favoritos o Recomendados

### ISSUE THREAD

**Issue by danielr460** [alfa-addon/addon#130]
Buenas, ayer instalando el addon para un compañero, me hizo pensar en esta sección. Hay 2 ideas:
1. Los canales que uno use (luego de cierta cantidad de veces) se guarden en una sección llamada canales favoritos.
2. (la parte dificil creo) que esta sección de favoritos se pueda guardar y realizar como un conteo y crea una sección de recomendados, o hacer un sistema de puntuación para que las personas que no saben a donde ir vayan a lo recomendado

**Comment by alfa-addon** [comment]
Hecho
