### ISSUE TITLE
No funciona en v3.9.18 en Leia 18.9 RPi 3

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#1307]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://paste.kodi.tv/uqevuculem

### Sistema operativo

ARM Raspberry Pi Libreelec 9.2.8 Leia 18.9 (32 bits)

### Versión de Alfa

3.9.18

### Versión de Kodi

Kodi 18

### Descripción del problema

La version 3.9.18 no funciona, la version previa la 3.9.17 sí funciona aún.

**Comment by SistemaRayoXP** [comment]
Efectivamente, es un problema introducido por unos cambios recientes a un par de módulos. Se verá qué solución inmediata se le puede dar para lanzar una actualización de emergencia que lo repare.

**Comment by SistemaRayoXP** [comment]
Hola. Actualiza a la 3.9.19, debería estar solucionado. Igualmente que la 3.9.18 se me volvió a olvidar incluir el fix de canales, así que reinicia Kodi tras actualizar y dale un par de minutos para que aparezcan los canales

**Comment by askotx** [comment]
Listo, ya funciona de nuevo, excelente!!
