### ISSUE TITLE
AnimeFenix, AnimeJL y VerAnime no funcionan

### ISSUE THREAD

**Issue by viseniv** [alfa-addon/addon#1318]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://paste.kodi.tv/ojetesuhiq

### Sistema operativo

Windows 11

### Versión de Alfa

3.9.22

### Versión de Kodi

Kodi 20

### Descripción del problema

En alfa hay múltiples canales de anime que no funcionan pero si sus respectivas webs, si le doy a los enlaces de las webs en el log me los abre perfectamente el navegador.
Estos canales son: animejl, animefenix, veranime

**Comment by SistemaRayoXP** [comment]
Solo uno de los canales tiene problemas como tal, y no es prioritario su reparación.

**Comment by viseniv** [comment]
AnimeJL ha vuelto a funcionar, pero ni Animefenix ni VerAnime funcionan
