### ISSUE TITLE
¿Por qué necesito fuente remota para que pueda ser instalado el complemento?

### ISSUE THREAD

**Issue by Edmartt** [alfa-addon/addon#1321]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://localhost.com/alfa

### Sistema operativo

Windows 10

### Versión de Alfa

3.9.22

### Versión de Kodi

Kodi 20

### Descripción del problema

No me queda claro por qué es necesario de alguna forma tener que apuntar a una fuente remota que si bien puede leerla y saber qué hay, se ve que no debería ser obligatorio, y pensarán que puede navegar y elegir el zip, pero no es así. Cada que se selecciona el zip, que uno prefiera directamente sin incluir fuente remota, ocurre un error en el que se declara que no hay la biblioteca js2py.

Si tenemos la opción de la instalación local esto no debería ser problema, hay quienes instalamos la fuente, además el addon de la web es el 1.8 cuando en el repo se está en la 3.9 ya.

**Comment by Edmartt** [comment]
¿Cerrado? ¿Cuál es la respuesta a esto?

**Comment by SistemaRayoXP** [comment]
Te lo resumiré así: no pareces tener conocimiento suficiente del funcionamiento interno de Kodi como para comprender la respuesta a lo que preguntas (si es que entiendes lo que estás preguntando).

Date una leída a la wiki de Kodi. También podrías haber abierto un issue sin la plantilla de reporte de error…

**Comment by SistemaRayoXP** [comment]
Cabe mencionar, estás confundiendo el add-on del repo con el add-on que provee el contenido como tal, ya que obviamente son versiones diferentes de dos add-ons diferentes.

**Comment by Edmartt** [comment]
Pregunto en base al funcionamiento de la aplicación y la opción que me da. Y dicha opción no es solo instalar desde una fuente remota, sino también local. Veo que me dan vueltas al asunto y no hay respuesta concreta a esto. Las preguntas siguen planteadas, si bien esto tiene que ver con Kodi, es más tema se este complemento, es el que produce el error, además tampoco responder la diferencia enorme de versiones que hay
