### ISSUE TITLE
Fallo dentro de los canales AnimeFLV, AnimeFLV.me y AnimeFLV. ru

### ISSUE THREAD

**Issue by RedTestament** [alfa-addon/addon#133]
Los listados de series y películas dentro de estos canales aparecen vacíos,

**Comment by Intel11** [comment]
Hola @RedTestament  tendrías que enviar un log porque actualmente está mostrando las listas de películas los 3.

Saludos.

**Comment by RedTestament** [comment]
@Intel11 Gracias por la atención, ya corregí el problema, desinstalando y reinstalando desde cero el addon.
