### ISSUE TITLE
[v3.10.0] Libereelec Kodi 18.9 en Raspberry pi no funciona

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#1355]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://paste.kodi.tv/jacequmebi

### Sistema operativo

ARM Raspberry Pi Libreelec 9.2.8 Leia 18.9 (32 bits)

### Versión de Alfa

3.10.0

### Versión de Kodi

Kodi 18

### Descripción del problema

La version [v3.10.0] no funciona actualmente. Solo envia notificación de error en Kodi, la version [v3.9.30] sí funciona

**Comment by SistemaRayoXP** [comment]
Intenta con la 3.10.1, hubo un error que dejó DOA a Python 2. Es lo que pasa con versiones mayores 🤷‍♂️

**Comment by askotx** [comment]
Probé la [v3.10.1] y ya se ejecuta el addon pero no regresa info de algun canal, con el que probe fue con animeflv y sale el mensaje de [**-No hay elementos que mostrar-**]

**Comment by askotx** [comment]
Aqui esta el log de Kodi: https://paste.kodi.tv/qomoharovi

**Comment by SistemaRayoXP** [comment]
Pues lo ideal es que abras otro issue... En fin, en el log veo el posible problema. Subí un fix. Si no te funciona, abre otro issue

**Comment by askotx** [comment]
Muy bien, lo hare
