### ISSUE TITLE
[v3.10.1] No muestra resultados de los canales

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#1356]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://paste.kodi.tv/qomoharovi

### Sistema operativo

ARM Raspberry Pi Libreelec 9.2.8 Leia 18.9 (32 bits)

### Versión de Alfa

3.10.1

### Versión de Kodi

Kodi 18

### Descripción del problema

La [v3.10.1] ya funciona el addon, sin embargo, no arroja resultado de los canales al ser seleccionado alguno, probado con Animeflv

**Comment by SistemaRayoXP** [comment]
De verdad que la tengo difícil para soportar a Python 2 :disappointed:. Reinicia Kodi y prueba de nuevo, en mis pruebas _parece_ que va bien, ya me comentarás

**Comment by askotx** [comment]
Ya habia reinciado Kodi para enviar el log mas corto, ¿hay alguna opcion en Alpha para limpiar cache que ayude? Igual pruebo de nuevo y aviso

**Comment by SistemaRayoXP** [comment]
Lo digo para que con el reinicio se aplique el último fix...

**Comment by askotx** [comment]
Con reiniciada sí funcionó

**Comment by SistemaRayoXP** [comment]
> Ya habia reinciado Kodi para enviar el log mas corto, ¿hay alguna opcion en Alpha para limpiar cache que ayude? Igual pruebo de nuevo y aviso

Imagino que al ser rapsberry+elec tu plataforma te es tedioso reiniciar. Para verificar fixes sin reiniciar puedes ir a Configuración/AJustes > Otras herramientas > Comprobar actualizaciones urgentes
