### ISSUE TITLE
Introduction page

### ISSUE THREAD

**Issue by edenmedia** [alfa-addon/addon#1357]
Hi, I discovered a bug in Alfa with  Android in the Firestick.  The Welcome page that normally shows up only when you first install Alfa, is now always popping up each time you click something  and each time you open Alfa. Please disable the welcome page because it is so annoying and bothersome. Thank you

**Comment by SistemaRayoXP** [comment]
I'm afraid that you should disable your aggressive cleaning add-on instead. The page wouldn't show if your cleaner only let Alfa register it has already been shown.

**Comment by edenmedia** [comment]
I don't have any cleaning addon just PVR Client and Alfa
