### ISSUE TITLE
¿Por que el codigo descargado en kodi es distinto al del repositorio?

### ISSUE THREAD

**Issue by ifcaro** [alfa-addon/addon#1364]
Ayer estuve mirando el codigo para optimizar la carga de los links de playdede que tardan mucho en algunos dispositivos y me di cuenta que el codigo que esta en la carpeta addons de kodi parece estar mas actualizado que el que hay en el repositorio.

¿Podeis indicarme la causa de que este codigo sea distinto y si realmente esta mas actualizado?

He hecho una rama https://github.com/ifcaro/alfa-addon/tree/zip donde se pueden ver las diferencias que hay.

Por ejemplo, [esta fraccion de codigo ](https://github.com/ifcaro/alfa-addon/commit/b65a6717a3a995991107c74afca67093220a1b4a#r150163891)no existe en el repositorio y no la he encontrado en commits anteriores

**Comment by SistemaRayoXP** [comment]
Esto lo podrías haber preguntado directamente en nuestro foro...

https://alfa-addon.com/temas/version-2-7.1380/

**Comment by ifcaro** [comment]
Muy bonito el foro, pero el codigo esta alojado aqui en github. Aun asi me he registrado y no he visto que ponga en ningun sitio el motivo de porque el codigo del addon es distinto al que hay en el repositorio.

**Comment by ifcaro** [comment]
La cuestión es que tanto la version que tengo instalada en kodi como la versión del repositorio figuran como la 3.10.2, de ahi es donde me viene mi duda. He desarrollado unas mejoras en el canal de playdede sobre el codigo que tengo instalado en kodi, y al ir a subirlo al repositorio me he dado cuenta de las diferencias, no se si el codigo del repositorio va por detras o por delante (aunque me parece mas avanzado el que tengo en kodi), por eso abri esta issue.

**Comment by SistemaRayoXP** [comment]
![Screenshot_20241211-032550_Kodi.png](https://github.com/user-attachments/assets/6cae38a3-e4fc-4da8-a419-b8401947f6ff)

¿Y que dice ahí, señor cuestiones?

Si gustas proponer mejoras, insisto, en el foro podemos darte asistencia con más facilidad. Leer un poco cómo otros han aportado podría ayudarte, pero es que leer, pedimos solo eso. Toda la información relevante a Alfa está en su foro. GitHub solo actúa como nuestro repositorio de código, no como sitio de documentación. Para eso está el foro.

Y respondiendo a tu pregunta de forma muy pero muy simplificada, y que espero te haga no tener que volver a preguntarla:

**_Kodi siempre tendrá las versiones de archivos más actualizadas de Alfa. El repo solo contiene lo último que se ha "fijado" en una versión._**

Y adicionalmente, si vas a sugerir cambios, lo mejor es que los dialogues primero **_en el foro_**. Así, puedes preguntar todo lo que necesites en el mismo tema/hilo, y podemos informarte de cambios que hayamos hecho post-lanzamiento, como en este caso con playdede. De otro modo, existe una gran posibilidad de que no aceptemos tu PR por tener conflictos de cambios con los que hicimos nosotros. Enviar el PR se vuelve una mera formalidad cuando tus cambios ya han sido discutidos y aprobados en el foro.

**Comment by ifcaro** [comment]
Siento no tener tanto tiempo libre como usted para pasar tiempo en foros, pero la verdad no tenía ni idea de que existiera dicho foro. Tan solo quería aportar a un proyecto de código abierto.

Esta explicación que me has dado ahora me la podrías haber dado en el mensaje inicial en lugar de redirigirme a un post de 2018 de un foro, previo registro, en el que encima no pone nada de lo que yo preguntaba.

No os preocupéis por la PR pues los cambios me los voy a quedar en mi repositorio, prefiero colaborar con comunidades menos toxicas.

Un saludo

**Comment by DieFeM** [comment]
Si te parece que, en menos de 24 horas, hasta 2 diferentes desarrolladores te contesten a tus preguntas es señal de una comunidad tóxica igual será menos tóxica la que te ignore, que es lo que deberíamos haber hecho. Ya verás como la próxima vez eres tu el que va al foro a preguntar. Aunque no será al nuestro. Agur.
