### ISSUE TITLE
tiwikiwi->filemoon

### ISSUE THREAD

**Issue by edenmedia** [alfa-addon/addon#1368]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

log

### Sistema operativo

Windows 10

### Versión de Alfa

3.10.3

### Versión de Kodi

Kodi 20

### Descripción del problema

Hola, el servidor "tiwikiwi" -> "filemoon" no funciona. ¡Gracias por todo el trabajo que hacéis y os deseo una Feliz Navidad

**Comment by SistemaRayoXP** [comment]
¿Y el log...?
