### ISSUE TITLE
Duda con Canal Series Lan

### ISSUE THREAD

**Issue by gurnay1973** [alfa-addon/addon#139]
Estimados, ocurre que en el listado de series. La única que no aparece y si esta en la pagina web es el laboratorio de dexter, habría forma de agregarla en el listado???. Tambien les recomiendo que agreguen danimados.com que también es muy buena.

Saludos.

**Comment by danielr460** [comment]
hola, ya se arreglo lo de serieslan, en cuanto a danimados.com, revisa esto y me das tus opiniones,
así se sube al alfa [https://drive.google.com/file/d/0B-GxlpMAaM6eaUFfdUhqalRXbDg/view?usp=sharing](url)
(Me falta seccion de peliculas)

**Comment by gurnay1973** [comment]
Esta buenísimo, muchas gracias.
Cuando crees que se lanzara la nueva versión???.
También informar que pelispedia no funciona ningún link y en su pagina si funcionan. A los Openload como que intentan cargar y no abre nada, ni siquiera arroja error de link caído.

**Comment by gurnay1973** [comment]
Hola estimado, vi que liberaron la nueva versión con series lan corregido, muchas gracias por eso.
En este momento sigue sin funcionar el canal peslispedia, no funciona absolutamente ningún link ni película.

**Comment by gurnay1973** [comment]
También los canales ver novelas online y ver telenovelas, tampoco están funcionando.

**Comment by danielr460** [comment]
eso ya quedo arreglado (lo de vertelenovelas, aunque sale en la próxima actualización), faltaría pelispedia pero el tema principal del "Issue" se soluciono.

**Comment by gurnay1973** [comment]
Estimado series lan ahora no funciona nada. Abre el canal y al seleccionar una serie ahorra error de estructura o conexión.

Saludos y gracias.

**Comment by danielr460** [comment]
Hola lo que sucede es que la solicitud javascript para desencriptar el vídeo fue modificada un poco

**Comment by gurnay1973** [comment]
Y se puede hacer algo???. Yo también soy programador y me gustaría ayudarlos a solucionar los canales que presentan problemas. Como puedo aprender a ver estos temas, me especializo en php y JavaScript 

Saludos.

**Comment by danielr460** [comment]
Es que no se, ven te cuento lo que se hacia antes se escrapeaban 2 datos en el link del vídeo y esos dos se mandaban a un PHP y se obtenían 3 datos el 3er dato se pasaba a la función txc (creo que se llamaba así) y ese devolvía el código del vídeo de openload, yo ya llegue al PHP pero ahora solo me llegan dos datos (0 y 404) entonces aquí me quedó porque se poco de PHP, y la función txc se buscaba en un js de la pagina web y se cambian a python pero no recuerdo en cual js era

**Comment by gurnay1973** [comment]
Con qué herramientas haces el debug del canal??

**Comment by danielr460** [comment]
Jajaja con Kodi :(

**Comment by danielr460** [comment]
https://drive.google.com/file/d/0B-GxlpMAaM6eTmVrMjN3YUMtR3c/view?usp=sharing mira se modifico la linea 137 (el nuevo php) y la linea 160 (el nuevo regex para capturar los dos valores que recibe la pagina php) por si alguien domina javascript

**Comment by danielr460** [comment]
Arreglado en https://github.com/alfa-addon/addon/pull/150

**Comment by danielr460** [comment]
Issue solucionado, cerrarlo por favor
Cualquier duda se responde mejor en: alfa-addon.ga
