### ISSUE TITLE
No funciona hdfull, powvideo.net, streamplay y kingvid

### ISSUE THREAD

**Issue by Deivid25** [alfa-addon/addon#160]
Hola, quiero reportar que la página hdfull no funciona en el complemento desde hoy, también dejo de funcionar los enlaces de powvideo.net, streamplay y kingvid, agradecería que lo arreglaran, un abrazo.

**Comment by vguardiola** [comment]
El problema parece ser que han capado la configuración del navegador, yo cambiando las cabeceras en el fichero httptools.py por las mismas que da mi chrome me ha funcionado.
yo he cambiado estas dos cabeceras:
default_headers["User-Agent"] 
default_headers["Accept"]

**Comment by numa00009** [comment]
Puedes ser mas concreto con respecto a lo del cambio de cabeceras?
Las de mi httptools.py son:
default_headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
default_headers["Accept"] = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"

**Comment by vguardiola** [comment]
Yo he puesto las mismas de mi navegador,chrome, yo creo que cambiandolas por unas diferentes ta te deberia ir

**Comment by alfa-addon** [comment]
cierro issue, streamplay esta funcionando, powvideo será arreglado en la próxima versión y kingvid no existe.

Gracias por tu reporte.
