### ISSUE TITLE
Problema con algunas series en Newpct1

### ISSUE THREAD

**Issue by carlosjfcasero** [alfa-addon/addon#167]
Parece que hay algún tipo de problema al acceder a determinadas series en el canal Newpct1 (La que se avecina, Sherlock, The walking dead, etc). El típico error de que la web ha cambiado la estructura. 
Adjunto fichero con la traza del error. Muchas gracias.
[Newpct1_error.txt](https://github.com/alfa-addon/addon/files/1463500/Newpct1_error.txt)

**Comment by alfa-addon** [comment]
corregido
