### ISSUE TITLE
Error al cargar serie en videoTeca

### ISSUE THREAD

**Issue by siul85** [alfa-addon/addon#17]
Buenas, se produce un error al realizar cualquier intento de importar una serie a la videoTeca de ALFA usando cualquiera de las siguientes formas:

1. Copiando la carpeta de la serie de la biblioteca de PelisALaCarta. A priori y si no me equivoco tienen la misma estructura y ALFA maneja los mismo ficheros. El único fichero que no importo es cuya extensión es "*.strm" pues si que contiene la diferencia de la ruta de acceso. Si accedo al la videoTeca da error, y si uso la herramienta de sobrescribir los Json, NFO y strm del menú de herramientas, también me da error.

2. Entrando en algún canal (por ejemplo HDFull) e importar de aquí la serie en cuestión. Dicha serie me la agrega (verificado mediante SAMBA desde mi PC), me escanea los datos de la misma (descarga el infoPlus) pero al intentar acceder a la videoTeca con el addon ALFA me da error. 

El error que siempre me devuelve está adjunto a este mensaje.
[error videTeca_siul85_20170806.txt](https://github.com/alfa-addon/addon/files/1203190/error.videTeca_siul85_20170806.txt)

¿alguna idea del motivo del error?

Muchas gracias y un saludo.

**Comment by alfa-addon** [comment]
Gracias por el reporte, en esta versión 1.5.1 esos problemas deberían de estar solucionados, para más información puede leer aqui como hacer el proceso. [http://www.mimediacenter.info/foro/viewtopic.php?f=6&p=49869#p49867](url)

**Comment by siul85** [comment]
OK, probado y ya todo bien ya. Cualquier cosa más os informo.

Un saludo y gracias por el curro.

**Comment by Shoaibkhan786** [comment]
Can I use your code?
