### ISSUE TITLE
Alfa no reproduce los torrents con quasar

### ISSUE THREAD

**Issue by susobaco** [alfa-addon/addon#175]
Hola, he probado unos cuantos, y no funcionan, el error del log de kodi es este:

18:41:35.611 T:140264555353856 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJwbGF5IiwgCiAgICAiY2F0ZWdvcnkiOiAiZ2hvc3Qgc2hlbGwiLCAKICAgICJjaGFubmVsIjogInRvcnJlbnRsb2N1cmEiLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiZm9sZGVyIjogZmFsc2UsIAogICAgImZ1bGx0aXRsZSI6ICJHaG9zdCBpbiB0aGUgU2hlbGwgW0JsdVJheSAxMDgwcHgyNjVdW0FDMyA1LjEgQ2FzdGVsbGFubyBBQzMgNS4xLUluZ2xlcytTdWJzXVtFUy1FTl0iLCAKICAgICJoYXNDb250ZW50RGV0YWlscyI6IHRydWUsIAogICAgImluZm9MYWJlbHMiOiB7CiAgICAgICAgIm1lZGlhdHlwZSI6ICJtb3ZpZSIsIAogICAgICAgICJwbG90IjogIiIKICAgIH0sIAogICAgInNlcnZlciI6ICJ0b3JyZW50IiwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIlbDrWRlbyBlbiB0b3JyZW50IiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwOi8vdG9ycmVudGxvY3VyYS5jb20vZGVzY2FyZ2FyLXRvcnJlbnQvOTcwMzZfZ2hvc3QtaW4tdGhlLXNoZWxsLWJsdXJheS0xMDgwcHgyNjUtYWMzLTUtMS1jYXN0ZWxsYW5vLWFjMy01LTEtaW5nbGVzLXN1YnMtZXMtZW4vIiwgCiAgICAid2FudGVkIjogIiIKfQ%3D%3D
18:41:35.611 T:140264555353856   ERROR: InputStream: Error opening, plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJwbGF5IiwgCiAgICAiY2F0ZWdvcnkiOiAiZ2hvc3Qgc2hlbGwiLCAKICAgICJjaGFubmVsIjogInRvcnJlbnRsb2N1cmEiLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiZm9sZGVyIjogZmFsc2UsIAogICAgImZ1bGx0aXRsZSI6ICJHaG9zdCBpbiB0aGUgU2hlbGwgW0JsdVJheSAxMDgwcHgyNjVdW0FDMyA1LjEgQ2FzdGVsbGFubyBBQzMgNS4xLUluZ2xlcytTdWJzXVtFUy1FTl0iLCAKICAgICJoYXNDb250ZW50RGV0YWlscyI6IHRydWUsIAogICAgImluZm9MYWJlbHMiOiB7CiAgICAgICAgIm1lZGlhdHlwZSI6ICJtb3ZpZSIsIAogICAgICAgICJwbG90IjogIiIKICAgIH0sIAogICAgInNlcnZlciI6ICJ0b3JyZW50IiwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIlbDrWRlbyBlbiB0b3JyZW50IiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwOi8vdG9ycmVudGxvY3VyYS5jb20vZGVzY2FyZ2FyLXRvcnJlbnQvOTcwMzZfZ2hvc3QtaW4tdGhlLXNoZWxsLWJsdXJheS0xMDgwcHgyNjUtYWMzLTUtMS1jYXN0ZWxsYW5vLWFjMy01LTEtaW5nbGVzLXN1YnMtZXMtZW4vIiwgCiAgICAid2FudGVkIjogIiIKfQ%3D%3D
18:41:46.253 T:140264205956864  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mAdding torrent from http://torrentlocura.com/descargar-torrent/97036_ghost-in-the-shell-bluray-1080px265-ac3-5-1-castellano-ac3-5-1-ingles-subs-es-en/
18:41:46.428 T:140264205956864  NOTICE: [plugin.video.quasar] [GIN] 2017/11/18 - 17:41:46 | 200 [0m|  175.553033ms | 127.0.0.1 |  [0m GET     /play
18:41:46.492 T:140266379151744   ERROR: PlayMedia could not play media: plugin://plugin.video.quasar/play?uri=http%3A%2F%2Ftorrentlocura.com%2Fdescargar-torrent%2F97036_ghost-in-the-shell-bluray-1080px265-ac3-5-1-castellano-ac3-5-1-ingles-subs-es-en%2F

Avisadme si necesitais algún dato mas.

Salud!

**Comment by Intel11** [comment]
Hola, prueba en desinstalar quasar y volverlo a instalar con la ultima versión.

Saludos.

**Comment by susobaco** [comment]
Bien, ya la tenía instalada la última versión. Reinstalé y todo perfecto, muchas gracias. Pede ser, que, como que he cambiado de partición, copié todo el directorio .kodi a la nueva, y hubiera perdido alguna ruta.
Salud y buen trabajo!
