### ISSUE TITLE
AutoPlay - Popup de error en el enlace

### ISSUE THREAD

**Issue by sergigonza** [alfa-addon/addon#190]
Buenas noches,

Cuando se esta utilizando el Autoplay en algun canal (a mi me pasa con seriesblanco) y falla algun enlace, aparece un popup indicando que ha habido un error en el enlace, que puede a ver sido borrado, etc ...

Esto es un poco rollo, porque si en algun video donde los enlaces estan casi todos borrados, tienes que estar continuamente dandole al ok, entonces el autoplay pierde un poco su sentido.

¿Se podria suprimir dicho mensaje/popup y cuando de un error en un enlace que continue al siguiente?
Se me ocurre que incluso se podria poner un mensaje en plan intentando enlace 1 de 4. y segun vaya fallando que vaya aumentando dicho contador, y asi se sabe que esta buscando enlaces ...

Muchas gracias por vuestro trabajo ;)

**Comment by danielr460** [comment]
Hola @sergigonza se tiene una primera solución para esto en https://github.com/alfa-addon/addon/pull/195, funciona cuando el vídeo ha sido borrado, etc. No funciona cuando el conector esta fallando, puede ser solucionado en una versión futura
