### ISSUE TITLE
He encontrado esto de E.T.2...

### ISSUE THREAD

**Issue by manel00** [alfa-addon/addon#2]
https://drive.google.com/folderview?id=0B0kEpcThYVvLSHNHZ1JIeEVHV3M

No funciona, pero no quedara mucho supongo...

**Comment by alfa-addon** [comment]
Si no me equivoco ET cerró su página

**Comment by manel00** [comment]
Es que no es ET

**Comment by alfa-addon** [comment]
mala mia, no me di cuenta que se trataba de otro ET, les vamos a dar un vistazo

**Comment by manel00** [comment]
Me lo han actualizado ;)

**Comment by manel00** [comment]
Se ha conseguido algo?

**Comment by alfa-addon** [comment]
se ha agregado un  ET en el addon, creo que no es el mismo que pusiste pero practicamente tienen el mismo contenido.

**Comment by manel00** [comment]
Teneis email como comunidad? Gracias

**Comment by devalls** [comment]
El ET que se ha añadido es una modificación en base a este nuevo site:
https://elitetorrent.website/
Que contiene la base de datos de la antigua ET. Además, actualizan por lo menos la sección de series.
