### ISSUE TITLE
Newpct no funciona

### ISSUE THREAD

**Issue by triki05** [alfa-addon/addon#204]
Sería interesante arreglar newpct, ya que hay muchas series y películas que en newpct1 en las que no hay torrent, mientras que en newpct sí. También sería interesante que en newpct1 se pudiera pasar de la página 2, ya que cuando le das a siguiente estando en la 2ª página, en mi caso la raspberry se queda congelada y ya no hace nada.

Muchísimas gracias por vuestro gran trabajo

**Comment by danielr460** [comment]
hola @triki05 vamos a mirar que se puede hacer y tal vez este la mejora en la nueva versión

**Comment by triki05** [comment]
@danielr460 Muchas gracias por tu respuesta tan rápida 👍 Es genial el trabajo que realizais

**Comment by alfa-addon** [comment]
corregido
