### ISSUE TITLE
Animeflv dejo de funcionar.

### ISSUE THREAD

**Issue by Ninoh-FOX** [alfa-addon/addon#208]
desde la semana pasada animeflv esta en blanco; jkanime sale la lista, pero da error al intentar reproducir cualquier video (algunas veces dice que el add es solo para kodi 17 en adelante, cuando estoy usando kodi 17 y 18!).

Hay más canales que no funcionan como documania y similares, ojala sean reparados pronto.

**Comment by Ninoh-FOX** [comment]
14:41:14.037 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:14.037 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:14.037 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:14.037 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:14.038 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:14.038 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:17.344 T:140146594805504   ERROR: ######## ERROR #########
14:41:17.344 T:140146594805504   ERROR:     [alfa.core.filetools.read] ERROR al leer el archivo: /home/ninoh-fox/.kodi/addons/skin.estuary/addon.xml
14:41:17.346 T:140146594805504   ERROR: ######## ERROR #########
14:41:17.346 T:140146594805504   ERROR:     [alfa.core.filetools.read] Traceback (most recent call last):
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/core/filetools.py", line 112, in read
                                                f = open(path, "rb")
                                            IOError: [Errno 2] No such file or directory: '/home/ninoh-fox/.kodi/addons/skin.estuary/addon.xml'
14:41:17.349 T:140146594805504   ERROR: ######## ERROR #########
14:41:17.349 T:140146594805504   ERROR:     [alfa.platformcode.config.verify_directories_created] Al comprobar o crear la carpeta de resolución
14:41:17.364 T:140146594805504   ERROR: ######## ERROR #########
14:41:17.364 T:140146594805504   ERROR:     [alfa.platformcode.config.verify_directories_created] Traceback (most recent call last):
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/platformcode/config.py", line 382, in verify_directories_created
                                                res = scrapertools.find_multiple_matches(data, '(<res .*?>)')
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/core/scrapertools.py", line 102, in find_multiple_matches
                                                return re.findall(pattern, text, re.DOTALL)
                                              File "/usr/lib/python2.7/re.py", line 181, in findall
                                                return _compile(pattern, flags).findall(string)
                                            TypeError: expected string or buffer
14:41:24.130 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:24.130 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:24.130 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:24.131 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:24.131 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:24.131 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:31.849 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:43.413 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:43.414 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:43.414 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:43.414 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:43.414 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:43.414 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:46.713 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:46.714 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:46.714 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:46.714 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:46.714 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:46.717 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:49.261 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:52.412 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:41:59.607 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:41:59.607 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:41:59.607 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:41:59.607 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:41:59.608 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:41:59.608 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:02.775 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:02.775 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:02.776 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:02.776 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:02.777 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:02.777 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:05.158 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:09.667 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:18.727 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:29.999 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:34.063 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:34.063 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:34.063 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:34.063 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:34.064 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:34.064 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:39.144 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:42:47.611 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:42:47.612 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:42:47.612 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:42:47.612 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:42:47.612 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:42:47.612 T:140146594805504 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -2; absolute index: -1) in another category in old setting condition "eq(-2,1)" for "downloadpath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-2,1)" of old setting definition for "downloadpath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -4; absolute index: -1) in another category in old setting condition "eq(-4,1)" for "downloadlistpath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-4,1)" of old setting definition for "downloadlistpath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: cannot reference setting (relative index: -6; absolute index: -1) in another category in old setting condition "eq(-6,1)" for "videolibrarypath"
14:43:02.975 T:140146193303296 WARNING: CAddonSettings[plugin.video.alfa]: failed to parse visible condition "eq(-6,1)" of old setting definition for "videolibrarypath"
14:43:06.969 T:140146193303296   ERROR: ######## ERROR #########
14:43:06.969 T:140146193303296   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 233, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/channels/documaniatv.py", line 58, in mainlist
                                                error, user = login()
                                              File "/home/ninoh-fox/.kodi/addons/plugin.video.alfa/channels/documaniatv.py", line 28, in login
                                                if "http://www.documaniatv.com/user/" + user in data:
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
14:43:10.100 T:140148346550656   ERROR: GetDirectory - Error getting plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJtYWlubGlzdCIsIAogICAgImNhdGVnb3J5IjogIkRvY3VtYW5pYVRWIiwgCiAgICAiY2hhbm5lbCI6ICJkb2N1bWFuaWF0diIsIAogICAgImNvbnRleHQiOiBbCiAgICAgICAgewogICAgICAgICAgICAiYWN0aW9uIjogImNoYW5uZWxfY29uZmlnIiwgCiAgICAgICAgICAgICJjaGFubmVsIjogInNldHRpbmciLCAKICAgICAgICAgICAgImNvbmZpZyI6ICJkb2N1bWFuaWF0diIsIAogICAgICAgICAgICAiZnJvbV9hY3Rpb24iOiAibWFpbmxpc3QiLCAKICAgICAgICAgICAgImZyb21fY2hhbm5lbCI6ICJkb2N1bWFuaWF0diIsIAogICAgICAgICAgICAidGl0bGUiOiAiQ29uZmlndXJhciBjYW5hbCIKICAgICAgICB9CiAgICBdLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHt9LCAKICAgICJsYW5ndWFnZSI6IFsKICAgICAgICAiY2FzdCIsIAogICAgICAgICJsYXQiCiAgICBdLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cDovL2kuaW1ndXIuY29tL3FNUjlzZzkucG5nIiwgCiAgICAidGl0bGUiOiAiRG9jdW1hbmlhVFYiLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidmlld21vZGUiOiAibGlzdCIKfQ%3d%3d
14:43:10.102 T:140148346550656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJtYWlubGlzdCIsIAogICAgImNhdGVnb3J5IjogIkRvY3VtYW5pYVRWIiwgCiAgICAiY2hhbm5lbCI6ICJkb2N1bWFuaWF0diIsIAogICAgImNvbnRleHQiOiBbCiAgICAgICAgewogICAgICAgICAgICAiYWN0aW9uIjogImNoYW5uZWxfY29uZmlnIiwgCiAgICAgICAgICAgICJjaGFubmVsIjogInNldHRpbmciLCAKICAgICAgICAgICAgImNvbmZpZyI6ICJkb2N1bWFuaWF0diIsIAogICAgICAgICAgICAiZnJvbV9hY3Rpb24iOiAibWFpbmxpc3QiLCAKICAgICAgICAgICAgImZyb21fY2hhbm5lbCI6ICJkb2N1bWFuaWF0diIsIAogICAgICAgICAgICAidGl0bGUiOiAiQ29uZmlndXJhciBjYW5hbCIKICAgICAgICB9CiAgICBdLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHt9LCAKICAgICJsYW5ndWFnZSI6IFsKICAgICAgICAiY2FzdCIsIAogICAgICAgICJsYXQiCiAgICBdLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cDovL2kuaW1ndXIuY29tL3FNUjlzZzkucG5nIiwgCiAgICAidGl0bGUiOiAiRG9jdW1hbmlhVFYiLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidmlld21vZGUiOiAibGlzdCIKfQ%3d%3d) failed
14:43:16.386 T:140148346550656  NOTICE: Storing total System Uptime
14:43:16.386 T:140148346550656  NOTICE: Saving settings
14:43:16.396 T:140148346550656  NOTICE: Saving skin settings
14:43:16.411 T:140148346550656  NOTICE: stop all
14:44:58.059 T:140146385086208  NOTICE: [plugin.video.quasar] [32mNOTI  library      ▶ doUpdateLibrary  [0mLibrary updated

**Comment by Intel11** [comment]
Hola, has backup y prueba borrando este archivo:

userdata\addon_data\plugin.video.alfa\settings.xml

Para doucumania, es parece un problema del canal, se verá el problema y se tratará de reparar.

Saludos
