### ISSUE TITLE
Mediaserver

### ISSUE THREAD

**Issue by susobaco** [alfa-addon/addon#217]
Hola, estoy en trsquel 8.0 (variate libre de ubuntu 16.04 xenial).Al arrancar el mediaserver, después de ejecutar el script.py , me salen una serie de errores.
1º .- se ejecuta con python2 o python3 ??
2º Error con python2:
_python alfa.py
Traceback (most recent call last):
  File "alfa.py", line 18, in <module>
    import WebSocket
  File "/media/Seguridad/Programes/alfa/addon-2.3.9/mediaserver/WebSocket.py", line 12, in <module>
    from core import jsontools as json_

3º Error con python3:
_python3 alfa.py
  File "alfa.py", line 60
    print platformtools.controllers[a].controller.client_ip + " - (" + platformtools.controllers[
                      ^
SyntaxError: invalid syntax_

¿me falta algún módulo?
Gracias.

**Comment by t1254362** [comment]
Python 2, por eso se te queda en el 3º caso, "print N" es de python 2, en python 3 es print(N)

El "script.py" realmente no es necesario ejecutarlo, solo era una cosa para convertir librerías o algo así (no lo recuerdo exactamente), pero en una instalación de 0 puedes ejecutar directamente alfa.py

Pero veo que tu 2º punto ya es lo que haces. Que raro, a mi me va sin problemas en un OSMC y Ubuntu.
