### ISSUE TITLE
Ayuda pelis24 reborn (no hay elementos que mostrar) mi regex o no lo se.

### ISSUE THREAD

**Issue by prpeaprendiz** [alfa-addon/addon#224]
Hola, alguien me podria ayudar con el canal pelis24.to
Quiero saber si mi regex esta mal o que esta mal, el canal ya estaba hecho, yo solo edite algunas cosas como los cambios del dominio y el https, y no aparecen las peliculas asi que edite las regex pero no me funcionan, podrian checarlo y ayudarme por favor, muchas gracias de antemano!.
[pelis24.zip](https://github.com/alfa-addon/addon/files/1836172/pelis24.zip)

**Comment by Intel11** [comment]
Hola, el problema son los patrones.

Cambia la linea 127:
`data = scrapertools.find_single_match(data, "dle-content(.*?)not-main clearfix")`

Por:
`data = scrapertools.find_single_match(data, "dle-content(.*?)clearfix")`

No se porqué pusiste en el patron:  not-main   ya que en el fuente de la pagina no existe esa cadena. 

Y cambia las lineas 129 hasta la 131:
```
patron = '(?s)<div class="section-items clearfix owl-movies.*?class="movie-item.*?class="movie-img img-box.*?a href="([^"]+).*?img src="([^"]+).*?alt="([^"]+)'
patron += '<div class="movie-series">(.*?)\((\d{4})\).*?'
patron += '<a href=[^>]+>([^<]+)</a>'

```
Por:
```
patron = '(?s)img src="([^"]+).*?alt="([^"]+).*?<a href="([^"]+)".*?'
patron += '\((\d+\)).*?'
patron += '<a href=[^>]+>([^<]+)</a>'

```

Y la linea 135:

`for thumbnail, url, title, year, quality in matches:`

Por
` for thumbnail, title, url, year, quality in matches:`

En ese for fijate que primero debe ir el "titulo" y despues el "url"

![image](https://user-images.githubusercontent.com/25161862/37775896-25e438a8-2db2-11e8-91e4-4e5a074a4b4e.png)


Con eso ya te aparece la lista de peliculas.

Trata de usar regex cortos para que sean mejor entendidos y faciles de editar :)

Saludos.

**Comment by prpeaprendiz** [comment]
OHHHHH! muchas gracioas iIntel11 por tu ayuda, como veras soy principiante en esto del regex, apenas y lo estoy entendiendo,  espero dominarlo rapido para colaborar mas en lo que se pueda.

**Comment by Intel11** [comment]
Hola, no te preocupes, cualquier duda, aquí estamos :)

Saludos.

**Comment by prpeaprendiz** [comment]
Hola y gracias de nuevo!, disculpa, pero en caso de que haya  captchas en los reproductores que se puede hacer? (findvideos). En pelis24. Estoy un poco perdido y con jaqueca :(. Podrias ayudarme por favor?, muchas gracias y saludos!.
