### ISSUE TITLE
Series añadidas desde "Buscar" salen con el icono "Lupa"

### ISSUE THREAD

**Issue by ghost** [alfa-addon/addon#256]
Todas las series que añadimos desde hace unas versiones (no se cuales, pero se que antes eso no pasaba ya que tengo series añadidas así con su carátula) desde la sección "Buscar" salen con el icono de la lupa en vez de con la imagen que se mostraba en la sección buscar (que tienen icono, no es que al ponerte encima de la serie saliera la lupa, o estuviera sin icono).

Esto lo he comprobado en SeriesBlanco y SeriesPapaya. Si la misma serie la busco por letra (en seriesblanco) Listádo alfabético -> [letra] -> ponerme encima de la serie y "Añadir a favoritos", entonces si sale con la carátula (pensaba que saldría el icono de la TV amarilla ya que se repeitiría el bug, pero no, ha salido su imagen OK)

**Comment by t1254362** [comment]
Creo que he visto algo más. Veo que el "añadir a favoritos" lo tenéis protegido por versión:
        if num_version_xbmc < 17.0 and \
                ((item.channel not in ["favorites", "videolibrary", "help", ""]


Es decir, realmente estoy viendo el añadir a favoritos de Kodi (no el que vosotros hicisteis) ya que estoy usando un Kodi actualizado (el último Kodi 17, que no es .0). Eso explica porque no veo el mensaje de "se ha añadido a favoritos" ya que es el propio Kodi quien gestiona esto.

Sin embargo, hace años, antes de que os diera / les diera a los devs originales por re-implementar el favoritos dentro del propio addon, yo diría que esto iba ok también cuando lo añadía Kodi. Es algo que no entiendo: El elemento al ser mostrado en la búsqueda Kodi (al poner la selección en el) muestra el thumbnail de la serie, pero al añadirlo sale el de la sección donde estabas (buscar), sin embargo si voy a A-Z muestra el thumbnail de la serie.

No entiendo nada O_o

**Comment by Alfa-beto** [comment]
Hola, he observado los problemas que comentas, en mi caso solo en el canal seriespapaya, lo extraño es que me sucedió con series que he agregado últimamente, pero para mi sorpresa si elimino esas series y las vuelvo a  agregar, los thumbnails son correctos.

**Comment by alfa-addon** [comment]
Solucionado
