### ISSUE TITLE
Casi cada vez que entro a Alfa me sale el mensaje de las palomitas

### ISSUE THREAD

**Issue by t1254362** [alfa-addon/addon#257]
El titulo ya lo describe perfectamente.

No estoy seguro, pero podría ser por esto?
def start():
    """ Primera funcion que se ejecuta al entrar en el plugin.
    Dentro de esta funcion deberian ir todas las llamadas a las
    funciones que deseamos que se ejecuten nada mas abrir el plugin.
    """
    logger.info()
    config.set_setting('show_once', True)

El start pone siempre a True el show_once, por lo que cuando vuelvo a entrar al addon, si Kodi lo ha cerrado (imagino) lo vuelve a poner a True.

Yo por ahora me lo quito, porque es un coñazo 🤣

**Comment by Alfa-beto** [comment]
Ya, hemos tenido bastantes reclamos por este mensaje inofensivo, por lo que lo desactivaremos en la siguiente versión, simplemente fue un intento de mensaje de bienvenida que seria utilizado en caso de necesitar transmitir información importante al usuario.

**Comment by t1254362** [comment]
El problema principalmente no es que salga un mensaje (que habría que ver la necesidad), si no que sale siempre.
En el "start" ponéis la variable a "True", por lo tanto cada vez que Kodi carga el addon vuelve a salir el mensaje, una y otra vez. No solo la primera vez (leyéndolo y desapareciendo para "siempre").

Esa variable se tenía que poner a False y no volver hasta que el mensaje cambie (y obviamente, que cambie por algún motivo: explicar algo que falle, etc.)

Para poder hacer eso supongo que se podría cambiar el sistema de un bool a un int. Entonces en la config guardaríais el config.store("mensaje_visto", 4) por ejemplo.
En el futuro mensaje se cambia la versión del mensaje:
mensaje_visto = 5
if (config.get("mensaje_visto") < mensaje_visto) {
    mostrar_mensaje
    config.store("mensaje_visto", mensaje_visto)
}

Y si no, ni número de mensaje ni ostias, guardar el mensaje a saco y hacer una compración:
mensaje_actual = "hola que tal"
mensaje_antiguo = config.get("mensaje");
if (mensaje_actual != mensaje_antiguo) {
    mostrar(mensaje_actual);
    config.set("mensaje", "mensaje_actual);
}
