### ISSUE TITLE
Tarda mucho al cargar dentro de videolibrary para listar las series

### ISSUE THREAD

**Issue by gacomun** [alfa-addon/addon#270]
Buenos días:
Tarda bastante para cargar las series en el apartado de videolibrary->series.
Y veo que es porque lista todos los ficheros de cada carpeta hasta encontrar "tvshow.nfo". No se si seria tan sencillo como cambiar recorrer todas las carpetas y añadirle este fichero para obtener la información o hay algo que se me escapa del código que hace que se pueda estropear.

Tengo cerca de 23.000 ficheros repartidos entre 140 carpetas.

**Comment by alaquepasa** [comment]
No es eso. Obtener los archivos y recorrerlos lo hace muy rápido, pero como yo también lo pensaba me lo he cambiado para que vaya directo al tvshow.nfo (de algo mas de 15000 archivos a mirar 85), y no se ha notado nada de nada. He puesto unos cuantos "time()" y ese loop lo hace en un momento.

El problema está en el render_items.

Obtener las series lo hace en menos de un segundo, pero después el render items tarda 35:

[render_items] Render time = 35.3643550873 | Info = 0.249493837357 | context = 27.6548016071
Nota: Info = setInfoLabels | context = set_context_commands

Y de los 35, 27 segundos es la generación del menú contextual.

Aun no lo he mirado en detalle, pero creo que el problema es el base64 que se generera del item que fue agravado cuando los items fueron creciendo con infoLabels (más cosas para convertir a base64) junto con que hay más elementos en el menú contextual.

**Comment by alaquepasa** [comment]
Acabo de probar a quitar el context_menu y he pasado de 40 segundos a 12, pero claro, se pierde el poder borrar la serie, etc. Sin embargo esto ahora ocurre en todas. Cuando antes ibas a un listado y decías "tarda 1 minuto porque son muchos elementos" (ejemplo: cuando te salen 100 links), pues ahora tarda segundos (como antiguamente).

Tal vez haya que mirar de conseguir poner un modo (configurable) que de los mínimos elementos (yo no quiero trailers, por ejemplo) sin sacrificar mucho la velocidad.

**Comment by gacomun** [comment]
Pues si, a lo mejor es interesante poder configurar el menu contextual. aunque yo realmente lo que utilizo es la biblioteca de kodi. Pero si eso tb ayuda a la carga de enlaces bienvenido sea. ^_^

**Comment by alaquepasa** [comment]
Lo tienes disponible desde el 26 de mayo: https://github.com/alfa-addon/addon/pull/278
Pero tienes que activarlo en preferencias, opción "Menús contextuales rápidos"
