### ISSUE TITLE
Uso de Beautifulsoup 4 de kodi

### ISSUE THREAD

**Issue by gacomun** [alfa-addon/addon#271]
¿Tenéis algún inconveniente en utilizar "script.module.beautifulsoup4"? para el tratamiento de paginas web bien formadas creo que es mejor.

**Comment by gacomun** [comment]
Entonces si le pongo una dependencia al plugin podría usarlo? es que hay algunas paginas que es mas sencillo scrappear asi.

**Comment by bugatsinho** [comment]
scraping paginas de web con bs4 no es rapido... mas rapido es con parsedom!
