### ISSUE TITLE
tvsinpagar y otros clones rotos en mediserver

### ISSUE THREAD

**Issue by alaquepasa** [alfa-addon/addon#272]
Como es habitual, la gente no se preocupa de la versión mediaserver :cry: 

En los nuevos canales clones de descargas2020 habéis puesto un import xbmc, lo cual hace que se rompa en la versión mediaserver.

En todos es lo mismo, hace esto:
```
    if xbmc.getCondVisibility('Window.IsMedia') == 1:
        unify_status = config.get_setting("unify")
```

Esto es el nuevo "import xbmcgui" que había en canales antiguos. Por suerte se había pasado la moda de poner cosas dependientes de XMBC en canales, pero ha vuelto.

**Comment by lopezvg** [comment]
Sentimos las molestias,  El cambio tenía un objetivo, aunque meramente cosmético.  Se arreglará en la próxima versión.

Mientras tanto, borra la línea if xbmc.getCondVisibility('Window.IsMedia') == 1:

**Comment by alaquepasa** [comment]
No problem, lo avisaba más que nada, por un lado por si el que lo puso (¿tu?) lo podía arreglar y para que se tuviera en cuenta en otras versiones (principalmente ahora que los canales van cayendo, no es plan de que los que queden / se añadan nuevos no vayan :laughing: )
