### ISSUE TITLE
PelisPedia y paginas con Sucuri

### ISSUE THREAD

**Issue by mrgaturus** [alfa-addon/addon#280]
Me puse a ver porque pelispedia ya no funcionaba. Resulta que ya no se puede hacer scraping porque el proxy nuevo de pelispedia pide JS para generar un cookie que permita acceder a la pagina
Observaciones del script:
- Está encriptado en Base64
- Ejecuta funciones que python hace pan comido, como los slices, concatenacion, letra de un string, etc
- Está Separado por 2 partes: una genera el uuid y la otra genera la palabra sucuri y despues ambas de concatenan al revez. no estoy seguro si siempre hace el mismo orden
- El Agent del header es obligatorio, si no. les saldra error de acceso

**Comment by Intel11** [comment]
Hola @mrgaturus el canal pelispedia ya está funcionando, la última versión de Alfa es 2.5.15

Actualmente no está funcionando los enlaces HTML5 pero en la página de pelispedia tampoco funciona.

Saludos.

**Comment by mrgaturus** [comment]
Una pregunta, ustedes como hicieron para saltarse el bucle infinito que avienta los links a la hora de usar el debugger?

**Comment by pipcat** [comment]
Habrá otras maneras de hacerlo, pero en este caso fue analizando el js en local y poco a poco ir desofuscando y viendo qué hacía. No fue fácil, tardamos unos días... ;-)

**Comment by mrgaturus** [comment]
Bueno pues yo casi lo logró usando el ublock, pero la limitante era que no dejaba inyectar scripts que no esten en el archivo built-in de ublock. era la primera linea del gkpluginphp.js que tenia ese bucle infinito, de resto ya se hubiera coronado desde hace rato

**Comment by mrgaturus** [comment]
Otra seria usar Greasemonkey
