### ISSUE TITLE
torrents android 6+

### ISSUE THREAD

**Issue by bugatsinho** [alfa-addon/addon#342]
no puedo usar torrents en mi tv box quw tiene android 6.
me dijo falta de libtorrent]
log https://pastebin.com/H6hEU53U

**Comment by Intel11** [comment]
Hola, tendrías que usar otro cliente torrent para kodi como quasar, torrentin, elementun, etc, pásate al foro de alfa para que busques información como se hace:

www.alfa-addon.com

Saludos.
