### ISSUE TITLE
Problemas en Amazon firestick TV

### ISSUE THREAD

**Issue by indiocochino** [alfa-addon/addon#371]
Al intentar añadir cualquier contenido a la videoteca, me da error y no deja crear la carpeta del contenido en la carpeta del addon/serie/(nombre de la serie) - no recuerdo la dirección completa.

**Comment by Intel11** [comment]
Hola, con la versión 2.5.28 se soluciona ese problema, que versión usas? de lo contrario necesitariamos el log detallado para revisar el problema.

Saludos.

**Comment by indiocochino** [comment]
Hola,
el Kodi, recién instalado 17.6, y la versión 2.5.28 del Alpha.

Aquí el log:

21:59:08.869 T:18446744072510781912  NOTICE: Starting Kodi (17.6
Git:20171114-a9a7a20). Platform: Android ARM 32-bit
21:59:08.869 T:18446744072510781912  NOTICE: Using Release Kodi x32 build
21:59:08.869 T:18446744072510781912  NOTICE: Kodi compiled Nov 14 2017 by
GCC 4.9.0 for Android ARM 32-bit API level 21 (API level 21)
21:59:08.869 T:18446744072510781912  NOTICE: Running on Amazon AFTT with
Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.54+
21:59:08.882 T:18446744072510781912  NOTICE: FFmpeg version/source:
ffmpeg-3.1-kodi
21:59:08.882 T:18446744072510781912  NOTICE: Host CPU: ARMv7 Processor rev
3 (v7l), 4 cores available
21:59:08.883 T:18446744072510781912  NOTICE: Product: full_tank, Device:
tank, Board: tank - Manufacturer: Amazon, Brand: Amazon, Model: AFTT,
Hardware: mt8127
21:59:08.884 T:18446744072510781912  NOTICE: External storage path =
/storage/emulated/0; status = ok
21:59:08.885 T:18446744072510781912  NOTICE: ARM Features: Neon enabled
21:59:08.885 T:18446744072510781912  NOTICE: special://xbmc/ is mapped to:
/data/data/org.xbmc.kodi/cache/apk/assets
21:59:08.885 T:18446744072510781912  NOTICE: special://xbmcbin/ is mapped
to: /data/data/org.xbmc.kodi/cache/apk/assets
21:59:08.885 T:18446744072510781912  NOTICE: special://xbmcbinaddons/ is
mapped to: /data/app/org.xbmc.kodi-1/lib/arm
21:59:08.885 T:18446744072510781912  NOTICE: special://masterprofile/ is
mapped to:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
21:59:08.885 T:18446744072510781912  NOTICE: special://envhome/ is mapped
to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
21:59:08.885 T:18446744072510781912  NOTICE: special://home/ is mapped to:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
21:59:08.886 T:18446744072510781912  NOTICE: special://temp/ is mapped to:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
21:59:08.886 T:18446744072510781912  NOTICE: special://logpath/ is mapped
to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
21:59:08.886 T:18446744072510781912  NOTICE: The executable running is:
/data/app/org.xbmc.kodi-1/lib/arm/libkodi.so
21:59:08.886 T:18446744072510781912  NOTICE: Local hostname: localhost
21:59:08.887 T:18446744072510781912  NOTICE: Log File is located:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp//kodi.log
21:59:08.888 T:18446744072510781912  NOTICE:
-----------------------------------------------------------------------
21:59:08.913 T:18446744072510781912  NOTICE: load settings...
21:59:08.968 T:18446744072510781912   DEBUG: CSettings: loaded settings
definition from special://xbmc/system/settings/settings.xml
21:59:09.041 T:18446744072510781912 WARNING: CSettingInt: unknown options
filler "audiocdactions" of "audiocds.autoaction"
21:59:09.068 T:18446744072510781912   DEBUG: CSettings: loaded settings
definition from special://xbmc/system/settings/android.xml
21:59:09.102 T:18446744072510781912  NOTICE: Float is supported
21:59:09.103 T:18446744072510781912   DEBUG: AESinkAUDIOTRACK - 32000
supported
21:59:09.104 T:18446744072510781912   DEBUG: AESinkAUDIOTRACK - 44100
supported
21:59:09.104 T:18446744072510781912   DEBUG: AESinkAUDIOTRACK - 48000
supported
21:59:09.105 T:18446744072510781912   DEBUG: AESinkAUDIOTRACK - 88200
supported
21:59:09.105 T:18446744072510781912   DEBUG: AESinkAUDIOTRACK - 96000
supported
21:59:09.155 T:18446744072510781912   DEBUG: Firmware implements AC3 RAW
21:59:09.214 T:18446744072510781912   DEBUG: Firmware implements EAC3 RAW
21:59:09.215 T:18446744072510781912  NOTICE: Found 1 Lists of Devices
21:59:09.215 T:18446744072510781912  NOTICE: Enumerated AUDIOTRACK devices:
21:59:09.215 T:18446744072510781912  NOTICE:     Device 1
21:59:09.216 T:18446744072510781912  NOTICE:         m_deviceName      :
AudioTrack
21:59:09.216 T:18446744072510781912  NOTICE:         m_displayName     :
android
21:59:09.216 T:18446744072510781912  NOTICE:         m_displayNameExtra:
audiotrack
21:59:09.216 T:18446744072510781912  NOTICE:         m_deviceType      :
AE_DEVTYPE_HDMI
21:59:09.216 T:18446744072510781912  NOTICE:         m_channels        :
FL,FR,FC,LFE,SL,SR,BL,BR,BC,BLOC,BROC
21:59:09.216 T:18446744072510781912  NOTICE:         m_sampleRates     :
32000,44100,48000,88200,96000
21:59:09.217 T:18446744072510781912  NOTICE:         m_dataFormats     :
AE_FMT_S16LE,AE_FMT_FLOAT,AE_FMT_RAW
21:59:09.217 T:18446744072510781912  NOTICE:         m_streamTypes     :
STREAM_TYPE_AC3,STREAM_TYPE_EAC3
21:59:09.232 T:18446744072510781912   ERROR: CSettings: unable to load
settings from special://masterprofile/guisettings.xml, creating new default
settings
21:59:09.264 T:18446744072510781912   DEBUG: CSkinSettings: no
<skinsettings> tag found
21:59:09.265 T:18446744072510781912  NOTICE: No settings file to load
(special://xbmc/system/advancedsettings.xml)
21:59:09.266 T:18446744072510781912  NOTICE: No settings file to load
(special://masterprofile/advancedsettings.xml)
21:59:09.266 T:18446744072510781912  NOTICE: Default Video Player:
VideoPlayer
21:59:09.266 T:18446744072510781912  NOTICE: Default Audio Player: paplayer
21:59:09.266 T:18446744072510781912  NOTICE: Disabled debug logging due to
GUI setting. Level 0.
21:59:09.266 T:18446744072510781912  NOTICE: Log level changed to
"LOG_LEVEL_NORMAL"
21:59:09.267 T:18446744072510781912  NOTICE: Loading player core factory
settings from special://xbmc/system/playercorefactory.xml.
21:59:09.268 T:18446744072510781912  NOTICE: Loaded playercorefactory
configuration
21:59:09.268 T:18446744072510781912  NOTICE: Loading player core factory
settings from special://masterprofile/playercorefactory.xml.
21:59:09.269 T:18446744072510781912  NOTICE:
special://masterprofile/playercorefactory.xml does not exist. Skipping.
21:59:09.673 T:18446744072510781912  NOTICE: ADDONS: Using repository
repository.xbmc.org
21:59:09.855 T:18446744072512237040  NOTICE: Trying to open: 44100
samplerate 12 channelMask 4 encoding
21:59:09.861 T:18446744072512237040  NOTICE:
CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format:
AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size:
60208 m_frames: 3763 m_frameSize: 8 channels: 2
21:59:09.969 T:18446744072510781912  NOTICE: InitWindowSystem: Using EGL
Implementation: android
21:59:09.970 T:18446744072510781912  NOTICE: Found resolution 1280 x 720
for display 0 with 1280 x 720 @ 50.000000 Hz
21:59:09.970 T:18446744072510781912  NOTICE: Found resolution 1280 x 720
for display 0 with 1280 x 720 @ 60.000000 Hz
21:59:09.970 T:18446744072510781912  NOTICE: Found resolution 1920 x 1080
for display 0 with 1920 x 1080 @ 24.000000 Hz
21:59:09.970 T:18446744072510781912  NOTICE: Found resolution 1920 x 1080
for display 0 with 1920 x 1080 @ 50.000000 Hz
21:59:09.971 T:18446744072510781912  NOTICE: Found resolution 1920 x 1080
for display 0 with 1920 x 1080 @ 60.000000 Hz
21:59:09.971 T:18446744072510781912  NOTICE: Found (1920x1080@60.000000) at
20, setting to RES_DESKTOP at 16
21:59:09.971 T:18446744072510781912  NOTICE: Checking resolution 16
21:59:10.024 T:18446744072510781912  NOTICE: GL_VENDOR = ARM
21:59:10.025 T:18446744072510781912  NOTICE: GL_RENDERER = Mali-450 MP
21:59:10.025 T:18446744072510781912  NOTICE: GL_VERSION = OpenGL ES 2.0
21:59:10.025 T:18446744072510781912  NOTICE: GL_SHADING_LANGUAGE_VERSION =
OpenGL ES GLSL ES 1.00
21:59:10.025 T:18446744072510781912  NOTICE: GL_EXTENSIONS =
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture
GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8
GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil
GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax
GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8
GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer
GL_OES_get_program_binary GL_ARM_mali_program_binary
GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map
GL_KHR_debug
21:59:10.931 T:18446744072512125304  NOTICE: Running database version
Addons27
21:59:12.155 T:18446744072510781912 WARNING: CSkinInfo: failed to load skin
settings
21:59:12.641 T:18446744072510781912 WARNING: JSONRPC: Could not parse type
"Setting.Details.SettingList"
21:59:13.738 T:18446744072510781912  NOTICE: initialize done
21:59:13.738 T:18446744072510781912  NOTICE: Running the application...
21:59:13.742 T:18446744072510781912  NOTICE: starting upnp client
21:59:13.757 T:18446744072510781912  NOTICE: GL_VENDOR = ARM
21:59:13.757 T:18446744072510781912  NOTICE: GL_RENDERER = Mali-450 MP
21:59:13.758 T:18446744072510781912  NOTICE: GL_VERSION = OpenGL ES 2.0
21:59:13.758 T:18446744072510781912  NOTICE: GL_SHADING_LANGUAGE_VERSION =
OpenGL ES GLSL ES 1.00
21:59:13.758 T:18446744072510781912  NOTICE: GL_EXTENSIONS =
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture
GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8
GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil
GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax
GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8
GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer
GL_OES_get_program_binary GL_ARM_mali_program_binary
GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map
GL_KHR_debug
21:59:13.759 T:18446744072523514832  NOTICE: ES: Starting UDP Event server
on port 9777
21:59:13.759 T:18446744072523514832  NOTICE: UDP: Listening on port 9777
(ipv6 : false)
21:59:14.404 T:18446744072512237040  NOTICE: Trying to open: 44100
samplerate 12 channelMask 4 encoding
21:59:14.413 T:18446744072512237040  NOTICE:
CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format:
AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size:
60208 m_frames: 3763 m_frameSize: 8 channels: 2
21:59:27.712 T:18446744072535486456   ERROR: GetDirectory - Error getting
22:01:08.550 T:18446744072547907536   ERROR: Previous line repeats 9 times.
22:01:08.551 T:18446744072547907536   ERROR: ######## ERROR #########
22:01:08.551 T:18446744072547907536   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:08.633 T:18446744072547907536   ERROR: ######## ERROR #########
22:01:08.633 T:18446744072547907536   ERROR:
 [alfa.core.channeltools.get_channel_parameters] favorites.json error
22:01:08.788 T:18446744072547907536   ERROR: ######## ERROR #########
22:01:08.788 T:18446744072547907536   ERROR:
 [alfa.core.channeltools.get_channel_parameters] setting.json error
22:01:16.754 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.754 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.781 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.782 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.815 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.816 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.848 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.849 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.883 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.883 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.919 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.919 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.956 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.956 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:16.983 T:18446744072549474824   ERROR: ######## ERROR #########
22:01:16.983 T:18446744072549474824   ERROR:
 [alfa.core.channeltools.get_channel_parameters] channelselector.json error
22:01:28.755 T:18446744072547281960   ERROR: ######## ERROR #########
22:01:28.756 T:18446744072547281960   ERROR:     [alfa.core.filetools.read]
ERROR al leer el archivo:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/settings_channels/autoplay_data.json
22:01:28.759 T:18446744072547281960   ERROR: ######## ERROR #########
22:01:28.760 T:18446744072547281960   ERROR:     [alfa.core.filetools.read]
Traceback (most recent call last):
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/filetools.py",
line 112, in read
                                                f = open(path, "rb")
                                            IOError: [Errno 2] No such file
or directory:
'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/settings_channels/autoplay_data.json'
22:01:28.761 T:18446744072547281960   ERROR: ######## ERROR #########
22:01:28.761 T:18446744072547281960   ERROR:     [alfa.core.jsontools.load]
**NO** se ha podido cargar el JSON
22:01:28.763 T:18446744072547281960   ERROR: ######## ERROR #########
22:01:28.764 T:18446744072547281960   ERROR:     [alfa.core.jsontools.load]
Traceback (most recent call last):
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/jsontools.py",
line 38, in load
                                                value = json.loads(*args,
**kwargs)
                                              File
"/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/json/__init__.py",
line 352, in loads
                                              File
"/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/json/decoder.py",
line 364, in decode
                                            TypeError: expected string or
buffer
22:01:29.088 T:18446744072547281960   ERROR: ######## ERROR #########
22:01:29.089 T:18446744072547281960   ERROR:
 [alfa.core.channeltools.get_channel_parameters] autoplay.json error
22:01:29.095 T:18446744072547281960 WARNING: Invalid media type "list"
22:01:35.391 T:18446744072510781912  NOTICE: Samba is idle. Closing the
remaining connections
22:01:45.046 T:18446744072552321960 WARNING: CSkinInfo: failed to load skin
settings
22:01:46.792 T:18446744072552321960   ERROR: EXCEPTION: Non-Existent
Control 0
22:02:49.633 T:18446744072550684512   ERROR: ######## ERROR #########
22:02:49.634 T:18446744072550684512   ERROR:
 [alfa.core.filetools.mkdir] ERROR al crear el directorio:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/videolibrary/SERIES/Juego
de Tronos [tt0944947]
22:02:49.641 T:18446744072550684512   ERROR: ######## ERROR #########
22:02:49.641 T:18446744072550684512   ERROR:
 [alfa.core.filetools.mkdir] Traceback (most recent call last):
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/filetools.py",
line 445, in mkdir
                                                os.mkdir(path)
                                            OSError: [Errno 2] No such file
or directory:
'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/videolibrary/SERIES/Juego
de Tronos [tt0944947]'
22:02:49.671 T:18446744072550684512   ERROR: ######## ERROR #########
22:02:49.671 T:18446744072550684512   ERROR:
 [alfa.core.filetools.write] ERROR al guardar el archivo:
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/videolibrary/SERIES/Juego
de Tronos [tt0944947]/tvshow.nfo
22:02:49.672 T:18446744072550684512   ERROR: ######## ERROR #########
22:02:49.673 T:18446744072550684512   ERROR:
 [alfa.core.filetools.write] Traceback (most recent call last):
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/filetools.py",
line 144, in write
                                                f = open(path, "wb")
                                            IOError: [Errno 2] No such file
or directory:
'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/videolibrary/SERIES/Juego
de Tronos [tt0944947]/tvshow.nfo'
22:02:49.687 T:18446744072550684512   ERROR: ######## ERROR #########
22:02:49.687 T:18446744072550684512   ERROR:
 [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/platformcode/launcher.py",
line 206, in run

videolibrarytools.add_tvshow(item, channel)
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/videolibrarytools.py",
line 622, in add_tvshow
                                                insertados, sobreescritos,
fallidos, path = save_tvshow(item, itemlist)
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/videolibrarytools.py",
line 319, in save_tvshow
                                                insertados, sobreescritos,
fallidos = save_episodes(path, episodelist, item)
                                              File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alfa/core/videolibrarytools.py",
line 360, in save_episodes
                                                raiz, carpetas_series,
ficheros = filetools.walk(path).next()
                                            StopIteration
22:03:07.001 T:18446744072510781912  NOTICE: Storing total System Uptime
22:03:07.002 T:18446744072510781912  NOTICE: Saving settings
22:03:07.037 T:18446744072510781912  NOTICE: Saving skin settings
22:03:07.051 T:18446744072510781912  NOTICE: stop all
22:03:07.058 T:18446744072510781912  NOTICE: stop player
22:03:07.078 T:18446744072510781912  NOTICE: ES: Stopping event server
22:03:07.088 T:18446744072510781912  NOTICE: stopping upnp
22:03:08.012 T:18446744072523514832  NOTICE: ES: UDP Event server stopped
22:03:08.037 T:18446744072510781912  NOTICE: clean cached files!
22:03:08.166 T:18446744072510781912  NOTICE: closing down remote control
service
22:03:08.167 T:18446744072510781912  NOTICE: stopped
22:03:08.369 T:18446744072510781912  NOTICE: destroy
22:03:08.370 T:18446744072510781912  NOTICE: unload skin
22:03:08.450 T:18446744072510781912 WARNING: Cleanup: Having to cleanup
texture lists/focus.png
22:03:08.587 T:18446744072510781912  NOTICE: unload sections
22:03:08.636 T:18446744072510781912  NOTICE: special://profile/ is mapped
to: special://masterprofile/
22:03:08.671 T:18446744072510781912  NOTICE: application stopped...

Un saludo,
Claudio
