### ISSUE TITLE
Felicidades, algun bug menor e ideas XD

### ISSUE THREAD

**Issue by Aisasemi** [alfa-addon/addon#41]
Primero que todo, felicidades el addon esta increible, y funciona muy bien a pesar de tener algun bug chorra.

El bug que me he encontrado es con AnimeFLV al parecer se come algunos capitulos el listado del addon, el caso con el que lo detecte fue con la serie Drifters, en el addon falta el capitulo 6 y en la web salen todos.

Encuanto a mejoras...

1.- Creo que estaria muy si se pudiese añadir una funcion opcional que vaya recorriendo enlaces del capitulo hasta dar con un enalce que este disponible, ademas de priorizar de algun modo los preferidos.

2.- Esto es mas complicado quizar pero, podria ser interesante poder configurar una que genere un cache en local de canales seleccionados y de este modo agilizar la navegacion sobre los mismos, ademas de funcionar en caso de caida del canal.

Bueno, son ideas o opiniones personales, lo que esta claro esque el addon es la caña!, y se que es más facil proponer ideas y que luego implementarlas XD.

**Comment by Inter95** [comment]
Gracias por tu sugerencias, tomamos nota de esas buenas ideas.
