### ISSUE TITLE
Workaround para Kodi Leia 18 beta1

### ISSUE THREAD

**Issue by atomizasser** [alfa-addon/addon#418]
https://github.com/alfa-addon/addon/blob/aaf6855de05597cd7ab8049265e6e203f6592e7e/plugin.video.alfa/platformcode/xbmc_config_menu.py#L472

Workaround para ejuctuar alfa en Kodi Leia 18 beta 1: eliminar lineas 472-476

**Comment by pipcat** [comment]
Qué valor tiene xbmcgui.__version__ en Leia 18 ? Para añadir un if y que no haga el setCoordinateResolution que ha quedado deprecated en Kodi 18, pero que se mantenga para las versiones inferiores.
