### ISSUE TITLE
Fallo Plugin HDFULL

### ISSUE THREAD

**Issue by advidsec** [alfa-addon/addon#443]
Para ver series o peliculas pendientes, da el siguiente error:

10:47:40.459 T:1451226032 WARNING: Invalid media type "list"
10:48:12.925 T:1451226032 WARNING: Previous line repeats 82 times.
10:48:12.925 T:1451226032   ERROR: ######## ERROR #########
10:48:12.925 T:1451226032   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 183, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/channels/hdfull.py", line 534, in findvideos
                                                decode_aa += aadecode(match)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/lib/aadecode.py", line 8, in decode
                                                data = text.split("+(ﾟДﾟ)[ﾟoﾟ]")[1]
                                            IndexError: list index out of range
10:48:18.564 T:1944219648   ERROR: GetDirectory - Error getting plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJmaW5kdmlkZW9zIiwgCiAgICAiY2F0ZWdvcnkiOiAiSERGdWxsIiwgCiAgICAiY2hhbm5lbCI6ICJoZGZ1bGwiLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiZm9sZGVyIjogdHJ1ZSwgCiAgICAiZnVsbHRpdGxlIjogIjEyeDAxIC0gW0NPTE9SIHdoaXRlc21va2VdW0JdVGhlIEJpZyBCYW5nIFRoZW9yeVsvQl1bL0NPTE9SXTogVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAidHZzaG93IiwgCiAgICAgICAgInR2c2hvd3RpdGxlIjogIlRoZSBDb25qdWdhbCBDb25maWd1cmF0aW9uIgogICAgfSwgCiAgICAidGh1bWJuYWlsIjogImh0dHBzOi8vaGRmdWxsLm1lL3RodW1icy9zaG93XzE1NjQ3OTI3YmQ1NWFkMmFlYTMxMjhiMDI1ODk3Y2Q2LmpwZyIsIAogICAgInRpdGxlIjogIjEyeDAxIC0gW0NPTE9SIHdoaXRlc21va2VdW0JdVGhlIEJpZyBCYW5nIFRoZW9yeVsvQl1bL0NPTE9SXTogVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidXJsIjogImh0dHBzOi8vaGRmdWxsLm1lL3NlcmllL3RoZS1iaWctYmFuZy10aGVvcnkvdGVtcG9yYWRhLTEyL2VwaXNvZGlvLTAxIyMjMTk2NjA4OzMiLCAKICAgICJ3YW50ZWQiOiAiVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iCn0%3d
10:48:18.566 T:1944219648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJmaW5kdmlkZW9zIiwgCiAgICAiY2F0ZWdvcnkiOiAiSERGdWxsIiwgCiAgICAiY2hhbm5lbCI6ICJoZGZ1bGwiLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiZm9sZGVyIjogdHJ1ZSwgCiAgICAiZnVsbHRpdGxlIjogIjEyeDAxIC0gW0NPTE9SIHdoaXRlc21va2VdW0JdVGhlIEJpZyBCYW5nIFRoZW9yeVsvQl1bL0NPTE9SXTogVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAidHZzaG93IiwgCiAgICAgICAgInR2c2hvd3RpdGxlIjogIlRoZSBDb25qdWdhbCBDb25maWd1cmF0aW9uIgogICAgfSwgCiAgICAidGh1bWJuYWlsIjogImh0dHBzOi8vaGRmdWxsLm1lL3RodW1icy9zaG93XzE1NjQ3OTI3YmQ1NWFkMmFlYTMxMjhiMDI1ODk3Y2Q2LmpwZyIsIAogICAgInRpdGxlIjogIjEyeDAxIC0gW0NPTE9SIHdoaXRlc21va2VdW0JdVGhlIEJpZyBCYW5nIFRoZW9yeVsvQl1bL0NPTE9SXTogVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidXJsIjogImh0dHBzOi8vaGRmdWxsLm1lL3NlcmllL3RoZS1iaWctYmFuZy10aGVvcnkvdGVtcG9yYWRhLTEyL2VwaXNvZGlvLTAxIyMjMTk2NjA4OzMiLCAKICAgICJ3YW50ZWQiOiAiVGhlIENvbmp1Z2FsIENvbmZpZ3VyYXRpb24iCn0%3d) failed

**Comment by Jesis8** [comment]
Si, da fallo desde ayer a la tarde/noche

**Comment by advidsec** [comment]
Seria error de HDFull ya que vuelve a funcionar
