### ISSUE TITLE
Megadede json + py (Adjuntos)

### ISSUE THREAD

**Issue by yukisekisan** [alfa-addon/addon#449]
Chicos, he conseguido meter Megadede solo reemplazando enlaces de Plusdede (actualmente deshabilitada), ¿Lo podéis añadir para el repo?, os mando update:
JSON: https://pastebin.com/NGdf3p2M
PY: https://pastebin.com/U4Myp9yP
Suerte que es un fork clavado al de plusdede.

PD: el active del json ya está a true y el logo pillé el de Twitter, pero si queréis poned otro.

Mil gracias!

**Comment by alfa-addon** [comment]
Gracias por colaborar con Alfa, ya está actualizado megadede en Alfa.

Saludos.
