### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by reddit-reaper** [alfa-addon/addon#494]
please update to a newer style of addon like exodus redux or seren. Change scrapers to jen style, use resolveURL so real-debrid and premiumize and other could be supported and basically make it an exodus redux clone but in spanish. that will make this addon 100 times better than it currently is. if you add cached torrent support from rd and pm you'll make this even better :)

**Comment by bugatsinho** [comment]
i think that the only thing this addon can offer on exodus redux is the domains so you can create spanish scrapers for lambdascrapers!
this addon it has different approach than exodus forks as it is like the old ReleaseHUB (multipages browser! and not multilinks browser)

**Comment by reddit-reaper** [comment]
i know but its such a pain to navigate lol a newer style addon with scrapers in an exodus format or even seren (with cached torrent support) would be way better honestly. I have to basically hide most the menu's from the inlaws for like search and stuff because it takes forever to finish
