### ISSUE TITLE
Felicidades por el proyecto

### ISSUE THREAD

**Issue by MakuSensei** [alfa-addon/addon#5]
Pos solo quiero felicitarlos por este proyecto y puedan mantener viva todo lo que aporto en estos tiempos pelisalacarta :) ojala este alfa addon siga para adelante y mejore aun mas de lo que fue su antecesor.

PD: si pueden agreguen mas servicios en la sección de animes :p especialmente AnimeYT

**Comment by alfa-addon** [comment]
Me alegro de que te guste el trabajo que nos dejó Jesús nuestro objetivo es seguir manteniendo el addon y tratar de hacer algunas mejoras, se irán agregando contenidos de anime paulatinamente.
