### ISSUE TITLE
Canal playview (si pueden por favor añádanlo)

### ISSUE THREAD

**Issue by prpeaprendiz** [alfa-addon/addon#55]
Playview.py
https://www.dropbox.com/s/4v2ygfsyy1k8jew/playview.py?dl=0

Playview.xml
https://www.dropbox.com/s/lkfufg1daym3b86/playview.xml?dl=0

Muchas gracias por todo saludos y ojalá lo puedan añadir!.

**Comment by prpeaprendiz** [comment]
Por cierto olvide comentar que obviamente los créditos del canal son de un desarrollador de la antigua versión; no hace falta mencionarlo por su anonimato pero estoy seguro que ustedes ya saben de quién se trata!.

**Comment by prpeaprendiz** [comment]
El creador de este canal es el que se encargaba de actualizar openload, espero que tengan permitido añadirlo.

**Comment by Inter95** [comment]
Gracias, posiblemente estará disponible en futuras versiones.
