### ISSUE TITLE
Nuevos cambios de Cloudflare

### ISSUE THREAD

**Issue by gdx2015** [alfa-addon/addon#591]
Esta noche, como sucedió hace unas pocas noches, algunos sitios con protección cloudflare devolvieron la lista vacía. Vi que en el cálculo de 'jschl_answer' introdujeron un nuevo parámetro. Algo como esto

` t = t.substr(r.length); t = t.substr(0,t.length-1); k = 'cf-dn-rCTSXug';
`

y eso 

` <div style="display:none;visibility:hidden;" id="cf-dn-PyYe">+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))</div>
`

**Comment by alfa-addon** [comment]
Solucionado.

Gracias por reportar.

Saludos.
