### ISSUE TITLE
SeriesBlanco: Filtro de idioma a nivel de canal

### ISSUE THREAD

**Issue by Sincasios** [alfa-addon/addon#628]
Antes en SeriesBlanco se podía configurar el filtrado a nivel de canal, pero tras un cambio ha desaparecido esa opción (ahora mismo SeriesBlanco ni sale en la sección de Configurar canales).

¿Se puede volver a poner esa sección para configurar el filtrado de idioma, y de enlaces directos / online?

Actualmente otros canales lo tienen, especialmente lo del idioma, que es muy útil.

**Comment by Sincasios** [comment]
He mirado el "json" del canal y veo que si tiene lo del idioma, solo que no aparece la opción por ningún lado. He comparado con otros canales sin mucho éxito (para entender que salga o no esa opción).

He probado a ponerle otra opción más que otros canales tienen, el filter links

```
,
    {
      "id": "filterlinks",
      "type": "list",
      "label": "Mostrar enlaces de tipo...",
      "default": 2,
      "enabled": true,
      "visible": true,
      "lvalues": [
        "Solo Descarga",
        "Solo Online",
        "No filtrar"
      ]
    }
```

y ya ha salido el menú de cofiguración con 3 opciones: Las 2 que ya tenía cuando no salía + la nueva opción inútil que le he puesto.

No solo sale, si no que está funcionando (la parte de idioma, claro).

Así que parece que hay algún problema que oculta las opciones de SeriesBlanco.

**Comment by Alfa-beto** [comment]
Esa opción no esta presente actualmente en el canal, pero puedes utilizar el filtro de idioma de autoplay, ademas cada serie permite tener su propio idioma independiente del filtro de autoplay desde el menú contextual (click derecho / pulsacion larga)

**Comment by Sincasios** [comment]
Pero si funciona. Me está filtrando, el problema es que no aparece el menú si no pongo una opción extra. Pero solo con las opciones que tiene el canal el filtrado funciona (ahora solo me salen cosas en castellano)
