### ISSUE TITLE
AnimeFLV.me

### ISSUE THREAD

**Issue by danielr460** [alfa-addon/addon#66]
Buenas realice unos cambios a unos canales, los agregaron y luego los quitaron, no entiendo porque, lo que yo hacia era agregar la opción de ver por openload, ya que las ultimas subidas de animeflv.me no es por el servidor directo si no por openload, me gustaria saber porque lo quitaron? si ustedes fueron los que me recomendaron subirlo por pr

**Comment by danielr460** [comment]
"fix python version, shadow names, findvideos method changed so we can get all servers without calling again itself" se llama asi mismo para poder ver el enlace de openload, no quite el findvideos anterior porque se necesita. Ejemplo de server directo: http://animeflv.me/Ver/21931/mobile-suit-gundam-wing-subbed/episodio-48/ Ahora, Ejemplo de openload http://animeflv.me/Ver/74048/dragon-ball-super/episodio-106/ que no me aparece el openload.co/ si no me aparece "play.openload.me" y alli si me aparece el openload.co, espero que puedan volver a poner a openload porque todo lo que sale de animeflv.me actualmente es con openload.

**Comment by alfa-addon** [comment]
Estimado danielr460 antetodo le agradecemos su aporte. Cambiamos varios archivos que usted modifico, pensamos que sería más sencillo aceptar su PR y modificarlo ya que había algunas fallas; que tener que explicar paso a paso que no estaba correcto para que lo fuera enviando.
Sobre animeflv.me, su cambio cuando "player" no se encontraba en la url se creaba una lista de items que volvia a llamar a findvideos, por lo que para listar un video de openload habia que pulsar dos veces, en vez de 1 como en el resto de canales.
Lo puede checar aquí https://github.com/alfa-addon/addon/blob/8c179d0d64c2165545be6e29843e7cad9b6b1112/plugin.video.alfa/channels/animeflv_me.py#L364

Vamos a revisar lo que nos comenta.

Para terminar pedirle disculpas si se ha sentido ofendido, no fue nuestra intención.

**Comment by alfa-addon** [comment]
Le comentamos las pruebas 😃

> Ejemplo de server directo: http://animeflv.me/Ver/21931/mobile-suit-gundam-wing-subbed/episodio-48/

Con su codigo se mostraban dos enlaces cuando sólo es uno, que es un enlace directo.

> Ejemplo de openload http://animeflv.me/Ver/74048/dragon-ball-super/episodio-106/

Tanto en su codigo como con el nuestro no funciona, por que el conector parece estar roto.

Dejamos codigo de nuestro findvideos retocado para encontrar servidores que no son openload, por si quiere testearlo.

Debe definir esta línea arriba del archivo junto al resto de imports.
```from core import servertools```

```python
def findvideos(item):
    logger.info()

    itemlist = []

    page_html = get_url_contents(item.url)
    regex_api = r'http://player\.animeflv\.me/[^\"]+'
    iframe_url = scrapertools.find_single_match(page_html, regex_api)

    iframe_html = get_url_contents(iframe_url)
    itemlist.extend(servertools.find_video_items(data=iframe_html))

    qualities = ["360", "480", "720", "1080"]
    for videoitem in itemlist:
        videoitem.fulltitle = item.fulltitle
        videoitem.title = "%s en calidad [%s]" % (videoitem.server, qualities[1])
        videoitem.channel = item.channel
        videoitem.thumbnail = item.thumbnail

    regex_video_list = r'var part = \[([^\]]+)'

    videos_html = scrapertools.find_single_match(iframe_html, regex_video_list)
    videos = re.findall('"([^"]+)"', videos_html, re.DOTALL)

    for quality_id, video_url in enumerate(videos):
        itemlist.append(Item(channel=item.channel, action="play", url=video_url, show=re.escape(item.show),
                             title="Ver en calidad [%s]" % (qualities[quality_id]), plot=item.plot,
                             fulltitle=item.title))

    return __sort_by_quality(itemlist)
```

**Comment by danielr460** [comment]
Bueno, casualmente openload dejo de funcionar hoy, pero en mi codigo si se muestra 2 veces, y si olvide mencionarlo en el pr que tocaba pulsar 2 veces por eso esperaba una colaboracion (hasta puse un hilo en mimediacenter), pero bueno, con ese codigo que me acaban de enviar veo que si muestra el enlace de openload y tambien los normales muchas gracias por llegar a una solucion.
Como recomendación sugiero que contesten a cada PR (en lo posible) para ver si estamos haciendo las cosas bien o mal. Gracias, probare cuando openload este arreglado (guiño: parece ser el mismo error del .mp4, aun no me atrevo a tocar servers)
