### ISSUE TITLE
newpct1 y seriesdanko 

### ISSUE THREAD

**Issue by jselu75** [alfa-addon/addon#68]
hola, en el canal de newpct1 cuando entro en series hd y pulso para ver una serie me sale el mensaje de error inesperado en el canal de newpct1 (puede deberse a un fallo de conexión la web a cambiado la estructura o error interno de alfa consulta el log y la ruta de la carpeta temp)
y en seriesdanko cuando entro en una serie me dice no hay elementos que mostrar.
gracias por el trabajo que hacéis

**Comment by xabier100** [comment]
A mi me pasa lo mismo
