### ISSUE TITLE
Uso del Addon para versioens anteriores de kodi

### ISSUE THREAD

**Issue by Kokokool** [alfa-addon/addon#685]
Tengo kodi Isengard (no puedo actualizarlo por tener android 4.2.2), el Alfa addon no puedo instalarlo me mando un error de script, es posible que haya una version anterior compatible con esta version de kodi? porfavor!

**Comment by mfuentescas** [comment]
Maybe you could use Mygica Media Center (it is a Kodi 17). I have the latest Alfa addon installed on it but I have Android 4.4.4.

I know the latest version of Mygica supports Android 4.4.2, but don’t know if you could find an older version for your 4.2.2 compatible with Alfa.

**Comment by mfuentescas** [comment]
Uso Mygica Media Center (Kodi 17) para mi Android 4.4.4 y tengo sin problemas el último Alfa. 

No sé si podrás encontrar una versión de Mygica compatible con tu Android 4.2.2 y Alfa. Toca buscar.
