### ISSUE TITLE
Canales Caídos

### ISSUE THREAD

**Issue by Fr4nkC** [alfa-addon/addon#739]
Hola buen día,

Detecte los siguientes canales OFFline, en mi repo opte por eliminarlos te dejo los nombres:

cinehindi.com
maxipelis24.org
verystreamtv.com
novelasgratishd.co
peliculashindu.com

Saludos.

**Comment by shlibidon** [comment]
Hola, menos verystreamtv.com, todos ellos están desactivados hace tiempo.
Saludos.
