### ISSUE TITLE
Varios servidores de video han dejado de funcionar

### ISSUE THREAD

**Issue by khaosjrm** [alfa-addon/addon#769]
Desde hace unos dias es imposible abrir enlaces de los siguientes proveedores de video:
- Powvideo
- Streamplay
- Clipwatching

Creo que Gamovideo tampoco anda fino.

Es posible arreglarlo? Gracias

**Comment by Sincasios** [comment]
+1
Yo también he notado que han dejado de funcionar. Eso si, llega a mostrar la pantalla de "Ver archivo" (es decir, no falla antes de encontrarlo y te sale el típico mensaje de error / el archivo no existe), si no que parece que lo encuentra, te dice que quieres hacer (Ver) y después intenta reproducirlo y falla.

**Comment by khaosjrm** [comment]
Anoche estuve haciendo un poco de debugging y pude comprobar que los enlaces generados dan un status code de 404, vamos que es como si no existieran.. rarooo rarooo
