### ISSUE TITLE
Plusdede deja de funcionar en la version 2.0.1

### ISSUE THREAD

**Issue by mik12able** [alfa-addon/addon#78]
Hola, mi problema es que al acceder a una pelicula/serie de plusdede me aparece un mensaje diciendo que puede haber un error de red o que la pagina haya cambiado.
¿Alguna solucion?

**Comment by mik12able** [comment]
Sigue sin funcionar en la 2.0.2

**Comment by alfa-addon** [comment]
gracias por tu reporte, plusdede esta funcional
