### ISSUE TITLE
Powvideo no sale en la lista de HDFull

### ISSUE THREAD

**Issue by Fran008** [alfa-addon/addon#790]
Buenos días. Lo primero es desearos que estéis bien en este confinamiento. Ahora más que nunca es cuando utilizo a saco estas herramientas de Internet.

Lo segundo, felicitaros por esta herramienta maravillosa... y lo tercero comunicaros el error que ahora tengo.

Al lío:

En la lista de HDFull (y seguramente en los demás canales también) ya no me aparecen los enlaces correspondientes a Powvideo. En la web sí que aparecen si entro por Chrome así que me dediqué a investigar un poco más.

Resulta que desde mi proveedor (Movistar) han bloqueado la web http://powvideo.net, así que en la lista de la web hdfull.io sale en la lista pero no accede a ningún vídeo porque fallan.

Me he conectado cambiando la IP por VPN con el plugin HOXX de Chrome... y entonces sí que funciona todo como siempre en la web http://hdfull.io

He intentado hacer lo mismo en Kodi, cambiando la IP por VPN con IPVanish... pero en Kodi no ha funcionado: cuando entro en el canal HDFull no me sale en la lista ningún enlace correspondiente a Powvideo.

Imagino que, según estas pruebas, el error ha de estar en la programación de Alfa, no sólo en el acceso capado de powvideo.net (puesto que eso debería habérmelo solventado IPVanish igual que en el ordenador lo he conseguido con HOXX).

Muchas gracias de antemano, y ánimo con el confinamiento. Salud para todos.

**Comment by Fran008** [comment]
Ahora tengo una duda porque la incidencia puede provenir de dos fuentes:

1- El bloqueo de powvideo.net
2- Que ahora han incluído un recaptcha para entrar en el video

Si es lo primero, con VPN debería bastar... pero si es lo segundo va a ser bastante más difícil.

**Comment by Fran008** [comment]
Siento mucho el follón... al final creo que en www.powvideo.net sí que entra, y no lo han bloqueado. Donde no puedo entrar es en http://powvideo.net sin poner las www. De ahí la confusión. Hay algo raro en todo esto, pero no entiendo el qué (porque con VPN en la web de HDFull sí que me deja entrar).

**Comment by Fran008** [comment]
Es como si en España hubieran quitado el acceso desde "http://powvideo", pero en el resto de los países no (y por eso ellos pueden entrar sin poner "www." Aquí en España poniendo las "www." entras pero si no las pones entonces no. Quizá por código se podría tener en cuenta esto en algún punto del programa...

**Comment by Fran008** [comment]
Parece ser que a streamplay.to le sucede lo mismo: ni sale en la lista de archivos ni (lógicamente) funciona.

Creo que son webs hermanas, porque ambas parecen ir de un "http://....embed" a un "http://...player"

He mirado el contenido de powvideo.json y, aunque no sé mucho de programación, he visto que aparece un link "https://powvldeo.cc/iframe-\\1-920x360.html" que creo que no se corresponde con el que usan actualmente. El que usan creo que es 920x560 y, en lugar de iframe, creo que usan "player".

**Comment by darkmaki** [comment]
@Fran008 
En la web de Alfa-Addon hay un hilo acerca de este tema:
https://alfa-addon.com/threads/no-funciona-powvideo-ni-streamplay.3340/page-2
En el hilo, uno de los miembros del equipo comenta lo siguiente a fecha de 23 de marzo de 2020:

> Estos servidores lamentablemente se han deshabilitado y es muy poco probable que vuelvan a activarse en el corto plazo.
