### ISSUE TITLE
Clientes de torrent externos

### ISSUE THREAD

**Issue by amon-ra** [alfa-addon/addon#792]
Soporta el plugin algún cliente de torrent aparte de elementum? 
Me gustaria lanzar los torrent en plexus pero no veo manera.

**Comment by lopezvg** [comment]
Soporta también Quasar, además de dos clientes internos basados en Libtorrent

**Comment by amon-ra** [comment]
ok. Muchas gracias

**Comment by amon-ra** [comment]
En que fichero del codigo se realiza la busqueda del cliente? a ver si puedo mandaros un pull request

**Comment by lopezvg** [comment]
platformtools
