### ISSUE TITLE
SetResolvedURL

### ISSUE THREAD

**Issue by danielr460** [alfa-addon/addon#80]
Buenas no se porque, pero pongo este modo, y luego pongo un capitulo de una serie que tengo en la biblioteca y se cambia a modo Direct, no se si puede echarme una mano con eso, o solucionarlo muchas gracias

**Comment by danielr460** [comment]
Revisando bien, esto sucede con los canales que tienen autoplay como seodiv (y pues al activar esta opcion)

**Comment by Alfa-beto** [comment]
El problema ocurre, como mencionas cuando se utiliza autoplay, se soluciono de forma temporal, por el momento autoplay funciona solo en modo directo, en los planes a futuro esta adaptarlo para que funcione con setresolved... por ahora solo direct

**Comment by danielr460** [comment]
Dale, muchas gracias, si en algo puedo colaborar para hacerlo compatible me avisan, porque se le puede sacar mas el jugo desde este modo, (ejemplo: una lista de reproducción desde la biblioteca, que reproduzca todo automático)

**Comment by alfa-addon** [comment]
Gracias por tu ofrecimiento, lo tendremos muy en cuenta.

Saludos!
