### ISSUE TITLE
No me permite descargar Ninguna temporada completa

### ISSUE THREAD

**Issue by santiagocarod** [alfa-addon/addon#823]
Creo que hay un problema con las peticiones AJAX a las paginas ya que no me permite descargar, verlas en si me deja pero al momento que quiero descargar una temporada completa no me permite. Descargar por capitulos si me permite

LOG: https://ufile.io/psg70b6j

Mas precisamente en el log me sale esto

![image](https://user-images.githubusercontent.com/23182382/84442953-f1a08480-ac3e-11ea-8636-d0c12107a1df.png)

**Comment by lopezvg** [comment]
Resuelto.  Reinicia Kodi y prueba.  Gracias por el log.

**Comment by santiagocarod** [comment]
Ahora funciona! Muchisimas gracias por todo!
