### ISSUE TITLE
Añadir el canal kbagi

### ISSUE THREAD

**Issue by charli55** [alfa-addon/addon#83]
Hola, me preguntaba si podéis añadir la web http://kbagi.com es como la que ya está diskokosmiko pero tiene más vídeo y asin poder usar la cuenta de esta web , he intentado añadirla con la opción que trae el adonis pero no funciona me da error y no tengo mucho más conocimiento de cómo hacerlo a sin que agradecería que la añadierais , gracias por el trabajo y la ayuda .

**Comment by alfa-addon** [comment]
Gracias por tu petición, es muy probable que sea agregado en futuras versiones.
