### ISSUE TITLE
Actualizar canal al ver video desde videoteca

### ISSUE THREAD

**Issue by sergigonza** [alfa-addon/addon#85]
Hola,

Estoy viendo que si un canal ha cambiado y existe una actualización,  esta solo se descarga si entras  a través del addon>canales.... en cambio, si accedes a un video desde la video teca,  intenta descargarse los enlaces pero no actualiza el canal a pesar de haber una actualización

Esto es muy interesante, bajo mi punto de vista, xq por ejemplo a mi me pasa q tengo las series en la videoteca y cuando quiero ver un capítulo sino me carga los enlaces o me da algun error, ya tengo q entrar a través del addon para que se autodescargue el canal actualizado, siendo un poco rollo
Muchas gracias! :)

**Comment by m588416** [comment]
No lo entiendo.

Si no me equivoco, en alfa no hay actualizaciones de canales individuales, se actualiza todo el addon (usando el repositorio de Kodi).

Eso si pasaba en pelisaalcarta, que al entrar al canal miraba la versión y se actualizaba si encontraba una versión más nueva,, pero diría que aquí lo quitaron (y de ahí que salgan versiones nuevas del addon)

**Comment by Alfa-beto** [comment]
Exacto, Alfa se actualiza por completo en cada actualizacion por lo tanto en cada actualizacion desde el repositorio se actualizan los canales que recibieron actualizaciones. Lo que mencionas y como te explica @m588416 sucedia en pelisalacarta, quizas estas confundiendo elementos que agregaste desde la biblioteca de pelisalacarta u otro fork con elementos de la videoteca de Alfa

**Comment by sergigonza** [comment]
Disculpar, tenéis razón.  Lo que me ha pasado es que no me funcionó dese la biblioteca y antes de entrar por el ad don,  actuAlice alfa entre medias y por eso pensé que seguía ocurriendo lo mismo que en pelisalacarta
Disculparme, ya cierro el hilo
Gracias
