### ISSUE TITLE
STREAMANGO no cargan enlaces

### ISSUE THREAD

**Issue by gualterb** [alfa-addon/addon#86]
STREAMANGO no cargan enlaces
Gracias

**Comment by alfa-addon** [comment]
Probamos enlaces y funciona perfectamente. sin aportar un caso especifico que de error, en futuros días cerraremos el issue.

**Comment by gualterb** [comment]
Hola! He probado de nuevo y en otros canales y no funciona. A la hora de darle a reproducir no inicia. He probado en raspberry y iPad y da el mismo problema.

**Comment by Intel11** [comment]
Hola, tendrías que colocar un log detallado, porque como dijo @alfa-addon los links de streamango funcionan.

**Comment by gualterb** [comment]
Hola! No se como copiar/pegar desde raspberry. He hecho foto http://i67.tinypic.com/n3lvlt.jpg

**Comment by Intel11** [comment]
Hola, puedes decir al menos en que canal y película te aparece ese mensaje de error? ya que según la captura (porque falta mas datos) es un video que ya no existe.

**Comment by gualterb** [comment]
En cualquier enlace de streamango del canal seriesblanco . Entro desde la web y si existe el vídeo. He probado con kabul servir y proteger el último capítulo.

**Comment by gualterb** [comment]
Probando en cualquier otro canal los enlaces de streamango me pasa igual. A veces da error de lista abortada. He probado a desinstalar e instalar y nada. A ver si alguien más le ocurre.

**Comment by alfa-addon** [comment]
@gualterb

**Comment by gualterb** [comment]
@alfa-addon si! De hecho he llegado a borrar todo, hacer instalación limpia (borrando la carpeta que queda guardada aún desinstalando) y nada. 
Viendo que es un problema aislado a ver cómo lo soluciono. Muchas gracias !.

**Comment by gualterb** [comment]
@alfa-addon acabo de hacer una prueba con Ipad que me falla igual y conectándome desde wifi (Movistar) no me va. Por 4G (Yoigo) si me va.

**Comment by gualterb** [comment]
Finalmente he desenchufado por completo también el router y al conectarlo de nuevo si funcionan. Lo había reiniciado por el botón y nada. Muchas gracias y disculpar!
