### ISSUE TITLE
Upstream not working

### ISSUE THREAD

**Issue by willsalasare** [alfa-addon/addon#874]

**Comment by shlibidon** [comment]
Hi, it's working for me, the only issue it's witht the test_video_exists function, so its not showing properly the notification  "[upstream] El archivo no existe o  ha sido borrado" when the file it was deleted. reset your kodi, and this time you will see it.

Thanks.

A mi me funciona, el unico problema es con la funcion  test_video_exists, asi que no se muestra como es debido la notificacion cuando el archivo ha sido borrado, reinicia kodi y está vez lo deberías de ver.

Gracias.
