### ISSUE TITLE
Troubles when adding to library or accessing items added to library

### ISSUE THREAD

**Issue by malversoft** [alfa-addon/addon#875]
The issue is not limited to one source, it seems to happen with all them.

The issue seems to be in the communication between the plugin and the library. Searching and viewing a serie seems to work ok. But adding a serie to the library or viewing series previously added to the library does not.

Here is a [debug log](https://ufile.io/eykmqs8x).
(Relevant part starts at: 2020-10-12 21:19:25.288)
For testing:

- I tried to open a chapter of a serie that I added to the Kodi library using Alfa.
Expected result: The list of sources to view the video from.
Actual result: An empty list of sources (I have checked that it has sources in the original channel web).
- I searched (and found) a serie with Alfa and tried to add it to the library.
Expected result: Chapters files added to my library under the library series directory.
Actual result: No directory or files are created under my library series directory (or anywhere else).

Both operations fail silently.

Thanks in advance for your help and good work.

**Comment by malversoft** [comment]
No news on this? Please, I cannot add any show to the library using Alfa, nor view from the library any show added with Alfa.

Currently running:
Kodi 18.9
Alfa 3.2.9

**Comment by Alfa-beto** [comment]
Hi, did you try to rename the plugin.video.alfa folder inside the user_data folder?(with kodi closed)
This will recreate the plugin.video.alfa folder, and then you must restart kodi and try again.

**Comment by malversoft** [comment]
That worked. Thank you very much!

To save me a lot of work, I have copied the old configuration files to the new configuration folder: settings_channels, settings_servers, settings.xml... and it continues working.

When dealing with that files I have discovered an issue. In the old configuration the library path had been misteriously resetted, so it was misconfigured.

I have (and always had) Alfa set to store items added to the library under the main Kodi library folder (special://profile/library/). Misteriously that path had been resetted to the "videolibrary" subdirectory under the plugin folder. Also, category subdirectory names "Series" and "Cine" had been resetted to "SERIES" and "CINE".
(To clarify things, that values had been misteriously resetted in the OLD configuration, the one that did not work)

That may explain why new series added to "the library" did not appear. They were added under the plugin subdirectory "videolibrary", while my Kodi looks for the library in its main user data subdirectory "library".
But I do not understand how that also prevented series previously added with Alfa to the main Kodi library (in the main user data library subdirectory) from showing any source.

Just for curiosity, in which circumstance the plugin configuration is resetted? I spent some time configuring Alfa in the past and I have had care of never coming back to defaults.

Again, thanks a lot for the plugin and for your help. Your suggestion really worked and also helped to diagnose things.

**Comment by lopezvg** [comment]
Hi, a problem has been identified and fixed on managing the settings, that might be the origin of your problem.

Secondly, in case the videolibrary path is lost for some reason, Alfa tries to rebuild it.  A sub-optimal behavior was identified on dealing with this process.  Now this process has been strengthen so it recreates successfully the path, providing there is still a valid reference in the system.
