### ISSUE TITLE
Downloads folder deleted at startup Alfa

### ISSUE THREAD

**Issue by aquylae** [alfa-addon/addon#906]
hi there,

when alfa starts the downloads folder is deleted. could I change this behaviour?
I'm using coreelec.

**Comment by lopezvg** [comment]
Alfa only deletes on start the folders "temp_torrents_Alfa" in the videolibrary path, and Kodi "subtitle" folder.  We do not delete any downloads folder.  We may remove some control files if they are found to be "zombies" from previous sessións.

Please, be more specific detailing the folder path than you think Alfa is removing.  Also supply a log to understand your ecosystem (https://alfa-addon.com/link-forums/pasos-para-un-correcto-reporte-de-error.24/)

**Comment by aquylae** [comment]
The problem was that I changed my "custom subtitle folder" to /storage/downloads/, and Alfa was deleting this folder as you told me. 

Many thanks for your help and for you work.

**Comment by lopezvg** [comment]
Ok, thanks for the warning.  I'll do something less aggressive. Regards

**Comment by aandroide** [comment]
after yesterday's corrections this problem returned and the download does not start
