### ISSUE TITLE
Error en kodi matrix sobre ubuntu bionic

### ISSUE THREAD

**Issue by susobaco** [alfa-addon/addon#966]
Hola, en el arranque me tira este error en el log.
 _ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'lib.alfaresolver_py3'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.alfa/videolibrary_service.py", line 440, in <module>
                                                       from lib.alfaresolver_py3 import updated, update_now
                                                   ModuleNotFoundError: No module named 'lib.alfaresolver_py3'
                                                   -->End of Python script error report<--_
Lo de la perdida de memoria es importante?
Salud!

**Comment by lopezvg** [comment]
Alfa requiere que dos módulos sean compilados con la version de Python 3.8.  Instala esa versión (3.8.5 por ejemplo) y conviértela en la prioritaria (o en la única mejor)
