### ISSUE TITLE
Problems with the Confluence Skin

### ISSUE THREAD

**Issue by irontes** [alfa-addon/addon#989]
Hi, 
When I use "News", "Global search" and/or "Favorite" using the Confluence Skin (Kodi Leia or Matrix) the "Plot", "Genre" and "Year" in the movie or tv series lists do not show up.  The only VIEW OPTION that I can choose from are:  Big List, Thumbnail and List and not Media Info. Do you have any suggestions how to fix this without having to change the Skin?
Thanks

**Comment by SistemaRayoXP** [comment]
Either update your installation with [this version of platformtools](https://github.com/alfa-addon/addon/files/6373262/platformtools.zip) or wait until the next version

**Comment by irontes** [comment]
Thank you very much I used the 'platformtools' you posted and everything works fine. Thanks again

**Comment by irontes** [comment]
I have just noticed that in "Favorites" the visualization is just like before nothing is showing up (meaning the plot and genre).
The only VIEW OPTION available are: Big List, Thumbnail and List and not Media Info.

**Comment by SistemaRayoXP** [comment]
Sorry, forgot to notify you. This was solved in version 3.4.1
